libretime/libretime

CONTRIBUTING.md, README.md
Solution: I am initializing this repo as per our discussions on [the LibreTime taiga](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork).
=> Problem: LibreTime needs initializing

mkdocs.yml
I've got too many branches open and will proceed to merge some of my older PRs right after i violate the C4 and merge this one ASAP.\
That way @korotkov13 will have something real to test when he gets back to #3.
=> Hotfix: Missing config change

.travis.yml
I'll stop soon, this should make em deploy to the right repo.
=> Proper target repo setup for mkdocs deploy

airtime_mvc/application/cloud_storage/Amazon_S3StorageBackend.php, airtime_mvc/application/common/UsabilityHints.php, airtime_mvc/application/configs/constants.php, airtime_mvc/application/configs/navigation.php, airtime_mvc/application/controllers/LibraryController.php, airtime_mvc/application/controllers/PodcastController.php, airtime_mvc/application/forms/EditUser.php, airtime_mvc/application/models/Preference.php, airtime_mvc/application/views/scripts/form/edit-user.phtml, airtime_mvc/application/views/scripts/form/preferences.phtml, airtime_mvc/application/views/scripts/user/add-user.phtml
Solution: Make billing configurable through LIBRETIME_ENABLE_BILLING and deactivate it
This should catch all the changes needed to deactive billing in LibreTime.
=> Problem: Billing is always on

airtime_mvc/build/airtime.example.conf
Takes care of task 1 from https://github.com/LibreTime/libretime/issues/24
=> Add default soundcloud config

airtime_mvc/application/services/PodcastEpisodeService.php, airtime_mvc/application/services/PodcastService.php, python_apps/airtime-celery/airtime-celery/tasks.py
I went ahead and cherry picked what is need to fix #26 and also added a check to not overwrite the album tag if one already exists.
@Robbt Could you check if this (https://github.com/LibreTime/libretime/pull/28/commits/2e9fc432b14899b9463260a26eeca9b890d2a954) still works with your pacifica downloads and I'll merge it.
=> Podcast naming feature as per #26

airtime_mvc/application/views/scripts/schedule/add-show-form.phtml
I did a quick check and added a show, ecasound is also still being installed, I see no further reason why this should not work but we will need to get some real tests done to be sure.
=> Re-enable record line in feature

.travis.yml
Travis can't do `env:` conditionals
=> Fix deploy condition on travis

airtime_mvc/application/configs/constants.php, airtime_mvc/application/configs/navigation.php, airtime_mvc/application/models/Auth.php
This is to get the help section to look better and point to somewhere users can find us. It also takes care of /dashboard/about and maybe more.
Some of the links I'm adding are 404 as we have yet to write them, I'd rather link something we have under our control rather than legacy transifex or similar.
=> Update naming and links in constants

airtime_mvc/public/js/airtime/library/library.js
=> Change inline manual links

airtime_mvc/application/configs/conf.php, airtime_mvc/application/configs/constants.php, airtime_mvc/application/controllers/ApiController.php, airtime_mvc/application/controllers/DashboardController.php, airtime_mvc/application/controllers/LoginController.php, airtime_mvc/application/models/Preference.php, airtime_mvc/application/upgrade/Upgrades.php, airtime_mvc/tests/application/helpers/AirtimeInstall.php
Everything should use the version from the VERSION file created by the installer with this.
=> Harmonize version reporting in ui and api

python_apps/airtime-celery/airtime-celery/tasks.py
The podcast downloader fails pretty badly when the podcast name contains non ascii chars. The main fail happens during logging; I have learnt way to much about pythons stupid unicode implementation.
This adds addtional debug logging and also outputs the real reason a download fails properly. The content of the tags should be written as UTF-8 or whater is input into it, this commit mainly touches (and fixes) logging.
=> Fix unicode issues in podcast downloader

airtime_mvc/application/models/Preference.php, airtime_mvc/application/views/scripts/listenerstat/index.phtml
Solution: Fix listenerstat page by deactivating the bandwidth limit stuff if none is configured.
=> Problem: sad tape error on /listenerstats

airtime_mvc/application/controllers/PreferenceController.php
Solution: Fix sad tape error when saving prefs w/o soundcloud
=> Problem: sad tape error when saving prefs w/o soundcloud config

python_apps/pypo/liquidsoap/ls_script.liq
According to the linked forum post at savonet/liquidsoap#390 this has been an issue for quite a while now.
I finally found [a file](http://rabe.ch/wp-content/uploads/2017/03/Rabe-Info-10.-Maerz-2017.mp3) that exhibits the issue and was able to test the fix properly.
=> Problem: liquidsoap sometimes clips audio

python_apps/api_clients/api_clients/api_client.py
=> Fix TLS support

python_apps/airtime_analyzer/tools/ftp-upload-hook.sh
I've just modifed the script, to not use anymore the SaaS config
=> ftp-upload-hook: Get rid of the SaaS stuff

installer/vagrant/ubuntu.sh
In the name was outdata so i changed it
=> Alsa-ubuntu.deb Update

Vagrantfile
Updated Vagrantfile as outlined in issue #158.
=> Switch Vagrantfile to use bento boxes for ubuntu #158

docs/index.md, docs/vagrant.md
So the docs reflect the changes from #159.
=> Update vagrant docs for new ubuntu boxes

CONTRIBUTING.md
In new issues we have been asking what distros installations are on quite often.
Ask for the distro and version in the "For bug reports, please provide the following details" section of CONTRIBUTING.md.
This should guide new Contributors to add the relevant information in their issues.
=> Ask for distro version in CONTRIBUTING.md

Vagrantfile, install, installer/systemd/airtime-celery.service, installer/vagrant/centos.sh, python_apps/airtime-celery/install/upstart/airtime-celery.conf
This is based on @bburton's work linked in #173.
I added 43eb777177b6edbfc8f9280ee8d6d0693e727d73 which removes installing the `std_err_override` module since it's only used by legacy media-monitor. I also fixed the "Installing Log Files" part that was apparently broken since ages (this might also help with #233 but I don't really believe my changes have any serious impact).
In 5013a76060c277f7811e01a004d39bf01a86f574 I removed starting all the services on install.  On a non-upgrade install, trying to start all the services during the install will lead to the installer failing since the config files needed by the services have not yet been created.
I tested this with heaps of distros... 
It works nicely on Ubuntu Trusty and Xenial. 
Debian Jessie also works as advertised. I had to give up …
=> Update installer with systemd detecting code

airtime_mvc/application/common/CORSHelper.php, airtime_mvc/application/forms/Login.php
I cleaned up the CORSHandler code a bit more and also rewrote the
helper to use the framework to access the request properly and
took care of also grabbing the request schema from the server.
Fixes #238, see #243 for analysis of the issue.
=> Fix non default local CORS URL case

python_apps/airtime_analyzer/airtime_analyzer/airtime_analyzer.py, python_apps/pypo/pypo/__main__.py
This fixes #234 and enables logging for pypo and airtime_analyzer.
=> Enable logging for analyzer and pypo

airtime_mvc/application/common/HTTPHelper.php, airtime_mvc/application/models/Schedule.php, python_apps/pypo/pypo/pypofile.py
Fix for issue https://github.com/LibreTime/libretime/issues/307
Additionally corrected some related bugs
=> Pypo permission fix

docs/install.md, docs/manual/preparing-the-server/index.md
A start at documenting the server install part. Adds docs and pointers for firewalling, PostgreSQL and RabbitMQ.
See #316 for the writing prompt 😉
=> Update preparing server docs

installer/lib/requirements-debian-jessie.apt, installer/lib/requirements-debian-stretch.apt, installer/lib/requirements-debian-wheezy.apt, installer/lib/requirements-ubuntu-precise.apt, installer/lib/requirements-ubuntu-trusty.apt, installer/lib/requirements-ubuntu-xenial.apt
#323 
Adds unzip and zip to requirements for composer to install cleaner/faster.
=> Add zip and unzip to requirements

python_apps/pypo/pypo/pypofile.py
This addresses that track time updating was broken on pure TLS systems.
See https://github.com/LibreTime/libretime/pull/309#issuecomment-333673773 and https://github.com/LibreTime/libretime/issues/312#issuecomment-333324835 for more info.
Thanks very much to @xabispacebiker for doing the grunt work on this, I just did some whitespace touchups expanded the try block to wrap a bit more code and created the PR.
=> Pypo track updating fix

README.md
=> Linking to forum from readme.md

docs/manual/preparing-the-server/index.md
A lot more to come across the whole documentation and source itself. :- ) Let's make LibreTime amazing.
=> Cleaned up preparing-the-server documentation page

mkdocs.yml
Fixing the discrepancy of language. :- )
=> Changing 'System' to 'Settings' in documentation

airtime_mvc/application/models/Show.php, airtime_mvc/application/models/ShowInstance.php, airtime_mvc/public/css/styles.css
This is a fix for my last PR with working logic - the previous one had some database issues after refactoring and will provide spurious results on the calendar. Please test and merge ASAP,
=> fixed autoplaylist database logic and icon position

airtime_mvc/application/configs/config-check.php, airtime_mvc/application/configs/constants.php
I think these are the in UI help links that got missed so far and should point to the discourse.
=> Fix remaining help links

install
=> Fix install --version

airtime_mvc/application/configs/navigation.php, airtime_mvc/application/layouts/scripts/layout.phtml, airtime_mvc/application/views/scripts/menu.phtml, airtime_mvc/application/views/scripts/partialviews/header.phtml, airtime_mvc/public/css/styles.css
This pullrequest makes some improvements to the interface as detailed in issue https://github.com/LibreTime/libretime/issues/313
It does not include a default logo as requested, but if anyone provides one then I can make the modifications to include it by default
=> Reconditioning interface personal block

Vagrantfile
=> Debian vagrant bump

docs/manual/secure-login-with-ssl/index.md
Just fixing root path as mentioned on https://github.com/LibreTime/libretime/issues/466#issuecomment-376287486
=> Fix documentation Root path

airtime_mvc/application/common/FileIO.php
Legacy upstream had a weird way of doing this that could lead to empty files being requested with a range header that did not match what was available on the server. I'm assuming this code used to work aroud some media-monitor feature that has been since refactored into analyzer which handles these cases properly.
Fixes #533
=> Always return proper file size

airtime_mvc/application/views/helpers/VersionNotify.php
This reverts commit 05b62f92586c035a64a797929f912fb7cefa82bb as per the discussion in https://github.com/LibreTime/libretime/issues/487#issuecomment-440411349.
=> Revert "Fixing failing version test"

docs/install.md
=> docs: add recomendations to instalation instructions

docs/install.md
I'm adding directions for how to download LibreTime as per a request from #596
=> Update install.md to add instructions for how to download codebase

airtime_mvc/public/css/fullcalendar.css, airtime_mvc/public/css/images/icon-clock.svg, airtime_mvc/public/css/styles.css, airtime_mvc/public/js/airtime/schedule/full-calendar-functions.js
unfortunately this also includes a bunch of formatting cleanup done automatically by my text editor, and now i don't have time to fix that.
=> add clock icon for autoloading playlists in calendar, remove empty show alert

airtime_mvc/public/css/add-show.css, airtime_mvc/public/css/styles.css
although the discussion in #338 gets into js frameworks, this was a simple css fix. tested in firefox and chrome. should be fine in ie.
=> make add show dialogue scrollable. fixes #338

airtime_mvc/application/forms/SmartBlockCriteria.php, airtime_mvc/public/css/playlist_builder.css, airtime_mvc/public/js/airtime/playlist/smart_blockbuilder.js, docs/manual/library/index.md
accompanies https://github.com/LibreTime/libretime/pull/607
=> copy changes and css for overflow label and help text

airtime_mvc/application/forms/SmartBlockCriteria.php, airtime_mvc/application/models/Block.php, airtime_mvc/application/models/Scheduler.php, airtime_mvc/application/models/ShowInstance.php, airtime_mvc/public/css/styles.css, airtime_mvc/public/js/airtime/playlist/smart_blockbuilder.js
So this is my work on building a smartblock that is aware of how much time is remaining in a show instance it is scheduled into and will grow or shrink based upon what is already scheduled. You can see #357 for more discussion on the rationale for the changes and the thought process behind the changes.
TODO still
=> Fill Remaining Time Smartblock Limit

dev_tools/release/release.sh
Adds the docs tooling back into the enriched tarball... Unlike phing they aren't actually huge and unused ;)
Fixes #643
=> Put docs into enriched tarball

airtime_mvc/application/controllers/LoginController.php, airtime_mvc/application/forms/Login.php, airtime_mvc/application/views/scripts/form/login.phtml
This fixes #506 - it just removes all of the recaptcha code because it depended upon a defunct service and was ineffective.
=> removed the recaptcha

airtime_mvc/tests/application/models/unit/PreferenceUnitTest.php
This deletes some dead commented code in a test class.
=> Remove dead, commented test

docs/manual/backing-up-the-server/index.md
See https://github.com/LibreTime/libretime/pull/691#issuecomment-453993906
=> Fix minor typo in backup commands

airtime_mvc/application/models/Scheduler.php
I'm pretty sure this fixes #708
=> passed $show variable when smartblock added via playlist

airtime_mvc/application/airtime-boot.php, airtime_mvc/application/common/AutoPlaylistManager.php, airtime_mvc/application/controllers/LibraryController.php, airtime_mvc/application/controllers/PreferenceController.php, airtime_mvc/application/forms/GeneralPreferences.php, airtime_mvc/application/models/Block.php, airtime_mvc/application/models/Preference.php, airtime_mvc/application/models/Scheduler.php, airtime_mvc/application/models/ShowInstance.php, airtime_mvc/application/modules/rest/controllers/MediaController.php, airtime_mvc/application/views/scripts/form/preferences_general.phtml, airtime_mvc/public/index.php, airtime_mvc/public/setup/database-setup.php, airtime_mvc/tests/application/bootstrap.php, composer.json, composer.lock
The basic functionality for adding an intro and outro playlist that will be added to autoplaylists.
It needs some debugging as it is giving an error related to the schedule already being updated so I suspect it is a timing thing and they need to be paused so that the previous schedule can complete before the next one happens.
This fixes #693
=> Add Intro and Outro playlist to Autoloading Playlists

composer.json
this fixes #709 or at least the should fix the issue identified with zend-view as a PR was merged already to fix it.
=> add master-dev for zend-view 7.3 fix

airtime_mvc/application/controllers/ApiController.php
Fixes the problem whereby an API request for onAirLightAction returned a 500 error. 
Fixes #726
=> Bugfix for #726. Fixes onAirLightAction returning 500 error

airtime_mvc/application/common/AutoPlaylistManager.php
=> fixed autoloading playlist to avoid errors when trying to schedule empty playlist

airtime_mvc/application/views/scripts/podcast/station.phtml, airtime_mvc/public/css/station_podcast.css
The podcast section is not displayed properly as attached image:
Apparently the relevant css was removed from styles.css, so instead of adding it again I just added additional "podcast-metadata-row" divs to the layout.  
Also removes the save button at the bottom, as it has no sense. (There is already one at the top)
=> Podcast interface fix

airtime_mvc/application/controllers/LibraryController.php, airtime_mvc/application/forms/EditAudioMD.php, airtime_mvc/application/models/StoredFile.php, airtime_mvc/application/models/User.php
=> Added the ability for admins to edit the owner of a track via the edit track interface

.travis.yml, composer.lock
Fixes #774 
I want to run the CI pipeline against the change to see what breaks
=> Update composer.lock versions

airtime_mvc/application/controllers/downgrade_sql/airtime_3.0.0-alpha.7.3/downgrade.sql, airtime_mvc/application/controllers/upgrade_sql/airtime_3.0.0-alpha.7.3/upgrade.sql, airtime_mvc/application/models/airtime/map/PodcastEpisodesTableMap.php, airtime_mvc/application/upgrade/Upgrades.php, airtime_mvc/build/schema.xml, airtime_mvc/build/sql/schema.sql
This fixes #780 - it is a simple database change and shouldn't impact things other than resolving this issue.
=> modified episodes_description to be longvarchar aka text

Vagrantfile, docs/vagrant.md, install
=> Deprecate Debian Jessie

airtime_mvc/application/common/WidgetHelper.php
=> Use user-defined timezone if it exists

mkdocs.yml
Fix rendering glitch introduced with #834.
=> Fix nav rendering with mkdocs

airtime_mvc/application/services/PodcastEpisodeService.php
This might fix #836 - I have not tested it yet.
=> added null to try to solve missing arguments bug for Podcast Publish function

python_apps/airtime-celery/airtime-celery/__init__.py, python_apps/airtime-celery/airtime-celery/celeryconfig.py, python_apps/airtime-celery/airtime-celery/tasks.py, python_apps/airtime-celery/setup.py
Cleans up formatting and adds python 3 compatibility. I mainly tested on debian-buster and centos to be sure that this still works on current targets.
=> Python3 cleanup in airtime-celery package

airtime_mvc/public/js/airtime/schedule/full-calendar-functions.js
This reverts commit 70424639a03f43e1eb6ed4b6edbae2a632545f50 (#858).
Fixes #865.
=> Revert ":recycle: (js) use proper date.format call"

airtime_mvc/application/models/Preference.php
This question from https://discourse.libretime.org/t/radio-home-page-title/300 makes sense to me and seems like low hanging fruit.
=> Do not add LibreTime to title if station name is set

docs/index.md
=> Add mattermost link to docs

airtime_mvc/application/common/AutoPlaylistManager.php
This fixes #881
It removes the intro and outro playlist add from the "repeat until full" content loop to avoid a "time remaining in smartblock" outro from filling a multi-hour show with a repeating outro.
=> Moved intro and outro autoplaylist out of repeat until full loop

docs/install.md
=> Document .deb install option

airtime_mvc/application/models/Schedule.php
Expand out currentShowID conditional
Fixes: #875
=> Fix live-info-v2 current track info

docs/api/openapi.yaml
This is an attempt to document the current API. The functions I have found to be broken are marked as such in the description of the function
=> Add OpenAPI doc of the current API

install
This should fix #929 but I haven't tested it.
=> fix rasbian debian 10 install

docs/manual/general/index.md, docs/manual/getting-started/index.md
=> Document CORS configuration better

airtime_mvc/build/sql/defaultdata.sql
=> Add default icecast admin username

install
This fixes the reprovisioning problem with icecast_pass issue.
=> made sure icecast_pass was copied to airtime directory upon reprovision

airtime_mvc/application/controllers/ApiController.php
Fix an issue that was causing live-info to fail when a presenter goes live.
=> live info api fix

docs/manual/host-configuration/index.md, docs/manual/troubleshooting/index.md
=> Add documentation for updating the config file

python_apps/pypo/pypo/mime.types
=> Added extra mime type for flac file

docs/database.md, docs/install.md, docs/manual/dashboard/index.md, docs/manual/getting-started/index.md, docs/manual/host-configuration/index.md, docs/manual/interface-customization/index.md, docs/manual/playlists/index.md, docs/manual/podcasts/index.md, docs/manual/smartblocks/index.md, docs/manual/stream-settings/index.md, docs/manual/upload/index.md, docs/manual/webstreams/index.md
Hey all, I updated a few pages on the Docs site to add clarity to the install process, explain an error that can happen when adding a new webstream, and adding instructions for changing the radio page background. This is my first time submitting a PR for the project, so please let me know if I need to change anything. Thanks!
=> Updating Assorted Documentation

docs/manual/getting-started/index.md, docs/manual/reverse-proxy/index.md, mkdocs.yml
Fixes #1025
Mentions #957, so will need updating when that is fixed. Also will need including in #1030
=> Add reverse proxy documentation

airtime_mvc/application/configs/constants.php, airtime_mvc/application/configs/navigation.php, docs/_data/navigation.yml, docs/_layouts/default.html, docs/contribute.md, docs/quickstart.md
=> Fixing copyright, organization as per @robbt

airtime_mvc/application/controllers/ApiController.php
this addresses #1066 (please edit out the whitespace change at the end of the file)
=> Prevent 500 errors when no content is available

docs/install.md
Thanks to Lordfader for spotting it
=> Fix NTP link in docs

uninstall
=> Rename Airtime to LibreTime in Uninstall script

python_apps/airtime-celery/setup.py
Workaround for #1084 until we can fix compatibility
=> Pin celery version until we can fix compatibility with celery 5

install
=> Enable icecast service during install

install
=> Add our PPA to Ubuntu installs

airtime_mvc/application/controllers/EmbedController.php, airtime_mvc/application/views/scripts/index/index.phtml
This changeset fixes this issue:
* https://github.com/LibreTime/libretime/issues/988
This changeset contributes in fixing this issue
* https://github.com/LibreTime/libretime/issues/957
=> Fix HTML iframe tag in EmbedController(s) and adopt relative URLs

docs/_docs/reverse-proxy.md, python_apps/api_clients/api_clients/api_client.py, python_apps/api_clients/tests/test_apcurl.py, python_apps/api_clients/tests/test_get_protocol.py, python_apps/api_clients/tests/test_requestprovider.py, python_apps/pypo/pypo/pypofile.py
=> Use force_ssl in python apps

python_apps/pypo/pypo/pypofile.py
=> fix: force_ssl logic in pypofile

docs/api/openapi.yaml
Add yaml schema link to specs
Bump specs to v3.1.x
=> Add openapi yaml schema

.gitignore, airtime_mvc/.gitignore, docs/.gitignore
Removed some duplicate entries, and split the root gitignore in multiple ones.
=> Enhance .gitignore

python_apps/api_clients/api_clients/version2.py
=> Fix python format call

python_apps/api_clients/api_clients/utils.py, python_apps/api_clients/api_clients/version2.py, python_apps/api_clients/tests/test_utils.py
=> Fix python 3.6 support in api_client v2

python_apps/airtime_analyzer/airtime_analyzer/cli.py, python_apps/airtime_analyzer/setup.py
Let the system daemonize the process.
Fixes #1232
=> Remove daemon helper from analyzer

install, python_apps/airtime_analyzer/setup.py
=> Install pycairo before PyGObject

python_apps/api_clients/api_clients/utils.py
Previously unhandled, the http requests should either fail hard, or
errors should be logged with details of the failed request.
Related-To: #1172 #1274
=> Handle bad http requests in api clients

utils/update-postgres-password, utils/update-rabbitmq-password
I use this often to make clean install on my staging environment, though it could be committed back to the main repo.
This is only for advanced user who might stumble on this file.
=> Add postgres and rabbitmq password update scripts

api/libretimeapi/models/authentication.py, api/libretimeapi/models/schedule.py, api/libretimeapi/serializers.py, api/libretimeapi/tests/test_views.py
Fixes: #1272 
Unit tests included
=> Fix v2 schedule API endpoint

install
Before the formatting, the check was useless.
The fixes from the formatting/linting PR messed the logic.
=> Fix installer bad logic

install
=> Fix default web_root

install
Reverts LibreTime/libretime#1298
Replaced by #1296
=> Revert "Fix default web_root"

.pre-commit-config.yaml
=> Upgrade pre commit hooks

installer/vagrant/debian.sh
Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929248
=> add apt update to accept release suite change

.github/workflows/test.yml, .github/workflows/tools.yml
- Lowercase registry organisation name
- Always use LibreTime's org dev image for tests
- Never build the dev image on forks
=>  Fix CI docker test image

python_apps/airtime-celery/README.md
I don't think I'll do much more, this part of the project need a lot of care, I'd rather wait for a proper cleanup to write a proper documentation.
=> Update celery worker README

python_apps/api_clients/api_clients/utils.py, python_apps/api_clients/api_clients/version2.py, python_apps/pypo/pypo/pypofile.py
This is not pretty and would really improve from an OO API Client (#1308). But it should fix some of the errors seen in #1302
=> Use api_clients method to update file size of items on the server

airtime_mvc/application/configs/navigation.php, airtime_mvc/application/controllers/LibraryController.php
Closes  #1320 
This simply hide the my podcast feature, as it isn't working yet. Might be removed in the future.
=> Hide My Podcasts feature

.github/workflows/tools.yml, python_apps/airtime_analyzer/packages.ini, python_apps/pypo/packages.ini, tools/packages.py
Start building docker dev images for testing purpose.
=> Prepare Debian 11 support

.github/workflows/tools.yml, python_apps/airtime_analyzer/packages.ini, python_apps/pypo/packages.ini, tools/packages.py
Start building docker dev images for testing purpose.
=> Prepare Ubuntu 20.04 support

.github/workflows/tools.yml
Fixes https://github.com/LibreTime/libretime/runs/3558353551?check_suite_focus=true#step:6:2883
=> Disable interactive frontend for apt in docker builds

python_apps/api_clients/api_clients/utils.py
One day, maybe one day we will lint our code !
=> Fix undefined variable

api/Makefile, api/setup.py, install, python_apps/airtime-celery/Makefile, python_apps/airtime-celery/setup.py, python_apps/airtime_analyzer/Makefile, python_apps/airtime_analyzer/setup.py, python_apps/api_clients/Makefile, python_apps/api_clients/setup.py, python_apps/pypo/Makefile, python_apps/pypo/setup.py, tools/Makefile, tools/python.mk, tools/requirements-dev.txt
Some extra changes I wanted to ship in the last PR.
And some install fixes.
I think we shouldn't install the scripts entry points in `/usr/bin`, as this is the path for system packages, using the default `/usr/local/bin` seems appropriate. @paddatrapper what do you think ?
=> Follow up #1339

.github/workflows/tools.yml
This will help allow modifications in CI or locally.
=> Allow ci image user to run sudo without password

Vagrantfile
=> use 1Gb of RAM on libvirt

airtime_mvc/application/modules/rest/controllers/MediaController.php
=> fix php include for zend file transfer

api/libretimeapi/tests/models/test_schedule.py, api/libretimeapi/tests/test_views.py, api/libretimeapi/views.py
Fixes: #1360 and fixes the API integration tests to pass
=> Correctly filter schedule items based on is_valid

airtime_mvc/packages.ini, install, packages.ini
=> Move legacy packages.ini to airtime_mvc

airtime_mvc/packages.ini
Closes #1256 if we keep being careful about using versioned packages.
=> Versioned php packages and add missing packages

.github/workflows/test.yml, Vagrantfile, analyzer/tests/cuepoint_analyzer_test.py, analyzer/tests/playability_analyzer_test.py, api/packages.ini, docs/_docs/vagrant.md, install, legacy/packages.ini, packages.ini, playout/liquidsoap/main.py, tools/packages_test.py
Replaces #1120. Includes better error reporting and correct dependencies. Fixes #1109.
To do:
=> Ubuntu 20.04 Support

.github/workflows/test.yml, Vagrantfile, install, legacy/packages.ini, uninstall, utils/update-postgres-password, utils/update-rabbitmq-password
Run DB tests on 20.04 and remove buster php 7.4 reference
=> Various 20.04 fixes

playout/setup.py
=> fix: declare pypo.notify module

.github/workflows/test.yml, Vagrantfile, analyzer/tests/cuepoint_analyzer_test.py, analyzer/tests/playability_analyzer_test.py, api/packages.ini, docs/_docs/vagrant.md, install, legacy/packages.ini, packages.ini
This is heavily inspired by #1168.
Closes #1271 
Needs more testing, specially on the following topics:
I think #1168 could reuse some of this PR to install the proper php packages.
=> feat: debian 11 support

.github/workflows/lint-pr.yml
This action requires a full version.
=> ci: pin action-semantic-pull-request version

shared/libretime_shared/app.py, shared/libretime_shared/cli.py, shared/libretime_shared/logging.py, shared/tests/logging_test.py
using a string flag is better when using environment variables.
=> feat: replace verbosity flag with log-level flag

legacy/packages.ini, tools/packages.py, tools/packages_test.py
This allow  to exclude entire sections and install the packages manually.
In this case I want to exclude apache related packages and install nginx.
=> chore: exclude packages sections using tools/packages.py

playout/libretime_liquidsoap/1.1/ls_script.liq, playout/libretime_liquidsoap/1.3/ls_script.liq, playout/libretime_liquidsoap/1.4/ls_script.liq, playout/libretime_liquidsoap/generate_liquidsoap_cfg.py, shared/setup.py
Fixes #1514
:warning: Please do not squash.
=> fix: playout logging

shared/libretime_shared/config.py, shared/tests/config_test.py
:warning: Please do not squash
=> feat(shared): tweaks

analyzer/libretime_analyzer/main.py, playout/libretime_liquidsoap/main.py, playout/libretime_playout/main.py, playout/libretime_playout/notify/main.py, shared/README.md, shared/libretime_shared/cli.py
Allow some customization of the decorator before decorating functions.
=> feat(shared): allow cli parametrized decorators

Makefile, install, legacy/build/airtime.example.conf, playout/install/systemd/libretime-liquidsoap.service, playout/install/systemd/libretime-playout.service, playout/libretime_playout/config.py, playout/libretime_playout/listenerstat.py, playout/libretime_playout/main.py, playout/libretime_playout/pure.py, playout/libretime_playout/pypofetch.py, playout/libretime_playout/pypofile.py, playout/libretime_playout/pypoliqqueue.py, playout/libretime_playout/pypoliquidsoap.py, playout/libretime_playout/pypomessagehandler.py, playout/libretime_playout/pypopush.py, playout/libretime_playout/recorder.py, playout/libretime_playout/testpypoliqqueue.py, playout/setup.py, shared/tests/config_test.py
:warning:  Please do not squash.
=> feat(playout): load config using shared helpers

.pre-commit-config.yaml, analyzer/libretime_analyzer/message_listener.py, analyzer/libretime_analyzer/status_reporter.py, analyzer/libretime_analyzer/steps/analyze_metadata.py, analyzer/libretime_analyzer/steps/organise_file.py, api/libretime_api/models/authentication.py, api/libretime_api/permissions.py, api/libretime_api/tests/runners.py, api/libretime_api/tests/test_permissions.py, api/libretime_api/tests/test_views.py, api/libretime_api/utils.py, api_client/libretime_api_client/utils.py, api_client/libretime_api_client/version1.py, api_client/libretime_api_client/version2.py, installer/icecast/install/icecast2-install.py, playout/libretime_liquidsoap/generate_liquidsoap_cfg.py, playout/libretime_liquidsoap/liquidsoap_prepare_terminate.py, playout/libretime_playout/main.py, playout/libretime_playout/pypofetch.py, playout/libretime_playout/pypofile.py, playout/libretime_playout/pypoliquidsoap.py, playout/libretime_playout/recorder.py, playout/libretime_playout/telnetliquidsoap.py, playout/libretime_playout/testpypoliqqueue.py, utils/airtime-silan, worker/libretime_worker/tasks.py
- Update pre-commit hooks
- add pyupgrade to keep the codebase modern 
As always :warning: Please do not squash
=> chore: update pre commit hooks

legacy/application/common/FileDataHelper.php
=> fix(legacy): only render if img creation succeed

.github/invite-contributors.yml
=> chore: remove broken invite-contributors config

legacy/build/sql/defaultdata.sql, legacy/build/sql/sequences.sql, legacy/build/sql/triggers.sql, legacy/build/sql/views.sql
=> fix(legacy): clean sql migrations files

shared/libretime_shared/config.py
Provide a dsn/url property for the database and rabbitmq configuration
=> feat(shared): add url/dsn property to config classes

api_client/libretime_api_client/version2.py, playout/libretime_playout/pypofetch.py, playout/libretime_playout/pypoliqqueue.py, playout/libretime_playout/pypopush.py
Fixes #1453 
:warning: Do no squash
=> fix(playout): webstream stopping on manual schedule fetching

install
I tried many ways to break the system locales, using localepurge, removing the entire locale dir, none of those things made playout fail.
Fixes #317
=> feat: remove locale generation from installer

docs/_docs/install.md
=> docs: recommend current LTS or stable distro

legacy/build/airtime-setup/forms/database-settings.php, legacy/public/setup/database-setup.php
=> fix(legacy): update setup with new db config schema

install
=> feat: remove unused ubuntu ppa

analyzer/Makefile, analyzer/libretime_analyzer/status_reporter.py, docs/getting-started/ssl.md, tools/python.mk
More linters and already catched some ugly hacks.
Please do not squash
=> chore: install bandit and flake8

analyzer/libretime_analyzer/message_listener.py
=> fix(analyzer): remove bad attributes in shutdown handler

api/install/systemd/libretime-api.service
Related to #1278
https://github.com/LibreTime/libretime/issues/1278#issuecomment-1032511663
=> feat(api): improve uwsgi systemd integration

analyzer/libretime_analyzer/pipeline/organise_file.py
=> fix(analyzer): update docstring for organise_file

shared/libretime_shared/config.py, shared/libretime_shared/datetime.py, shared/libretime_shared/logging.py, shared/tests/datetime_test.py
Please de not squash :warning: 
Fixes and small additions.
=> feat(shared): improve shared

docs/admin-manual/setup/install.md, docs/admin-manual/setup/upgrade.md, docs/releases/3.0.0-alpha.00.md, docs/releases/3.0.0-alpha.01.md, docs/releases/3.0.0-alpha.02.md, docs/releases/3.0.0-alpha.03.md, docs/releases/3.0.0-alpha.04.md, docs/releases/3.0.0-alpha.05.md, docs/releases/3.0.0-alpha.06.md, docs/releases/3.0.0-alpha.07.md, docs/releases/3.0.0-alpha.08.md, docs/releases/3.0.0-alpha.09.md, docs/releases/3.0.0-alpha.10.md, docs/releases/_release-head.md, docs/releases/unreleased.md, website/docusaurus.config.js, website/src/components/TarballLink.tsx
Fixes #1535 
:warning: Please do not squash
=> chore: import relases notes from release pages 

install
=> fix: change celery user in worker service file

website/docusaurus.config.js, website/package.json, website/yarn.lock
This should allow to generate mermaid graph on the fly directly on the website.
Documentation such as https://github.com/libretime/libretime/issues/1610, https://github.com/libretime/libretime/pull/1543#issuecomment-1047165164 or https://github.com/libretime/libretime/pull/1644#issuecomment-1052901434 will be easier to integrate.
=> docs: add mermaid graph generation

install
=> fix: add PPA for newer liquidsoap version on Ubuntu

worker/install/systemd/libretime-celery.service
=> feat(worker): add service log filepath

docs/releases/3.0.0-alpha.11.md, website/vars.js
Preparing the 3.0.0-alpha.11 release.
What do we want to merge before releasing this ?
- #1568 (only website related but this new release note will land there)
- #1608
-  #1625
- #1624 ? I think with a bit of testing before releasing this change is not that risky.
- #1606
- #1663
=> chore: release 3.0.0-alpha.11

.github/workflows/api-schema.yml
Fixing the commit message and use conventional commits for the commit message.
=> ci: update api-schema commit message

website/docusaurus.config.js, website/package.json, website/redirects.js, website/yarn.lock
=> docs: add website redirects

api/pyproject.toml, api/setup.py
=> chore(api): add mypy django stubs plugins

.github/workflows/tools.yml, analyzer/packages.ini, playout/packages.ini, tools/packages.py
Some `packages.ini` files were not updated to support jammy because I could not test the outcome. (mainly referring to the php stack)
=> ci: build test images for ubuntu jammy

.github/workflows/test.yml
=> ci: simplify legacy test matrix

install
=> fix(installer): install software-properties-common when required

.github/workflows/docs.yml, .github/workflows/website-preview.yml, .github/workflows/website.yml, website/docusaurus.config.js
Once this is merged, a member of LibreTime can trigger a website preview deployment by commenting the pull request with the command **/deploy-website**. To clean the deployment, you need to close the pull request.
=> ci: website preview workflow

.github/workflows/command.yml, .github/workflows/website-preview-command.yml
The new command dispatch workflow require a service PAT to trigger the underlying workflow.
I can't decide if we want to call this a BOT_PAT or SERVICE_PAT.
=> ci: setup command dispatcher

docs/developer-manual/README.md, docs/developer-manual/design/_category_.yml, docs/developer-manual/design/architecture.md
old: https://mermaid.live/edit#pako:eNp1VNtq3DAQ_RWhpxSS_YClFNpuoYENbEkhD_ISxtLsWkS2HF26hDj_Xl2srL0Xv2jmnKPRaGbkd8q1QLqkO6UPvAHjyN9V1ZHwtdDBHs0Ne8jG9kvGe18ryW_YJq0Rzbj19d5A3xBuEBw-W96g8ArZz-QT1yAp2DZvid8Ba-h79oQ1CeuEOMbTBtkP4C_YiQmfckRrQ27P0Ev2kG3yfXN_oopsjH_OHLR5QcOe0jLhwknZScbJ_XoFb8fbbYJ37W5Rqb1LmrBOGCVfvRRWQ8_Y-tPeThSSIwfrGLvPxpRrlGXs9_qxYJMsS0VePXpkn0X5E90iF-CgBhvo1WhFZtZ1cnf3jQy_hHTD2KEiyF7iQ10zFowElMBzdJbSxTzJ16jLzRhPSfZJ0Ks7J2Mw15wndjXG2KtxxrMTmAX5J6HoSdYvLh1ZtqTC4WK_IEIfOqVBkJ1UOJAzZTr2OAiZPPop0jgFF7kwBeU--U0mtHTrBB7W0jrshnnES4IUNpL0lrZoWpAi_B_eI1bRMOgtVnQZTIE78MpVtOo-gtT3ocgYJ0YbutyBsnhLwTv9-NZxunTGYxGtJISX1I6qj_-wmXoB
[![](https://mermaid.ink/img/pako:eNp1VG1r2zAQ_itCnzpo8wPCGGzLYIUUMjLoBzmUs3WJRWXL1ctCqfvfpxcrsRPHX3T3PI_udKeTP2ilONIl3Ut1rGrQlvxdFS3xXwMtHFDfsadk7L4kvHOlFNUd28Q1o …
=> docs: create architecture design document

.github/workflows/website-preview-command.yml
=> ci: fix website preview cleanup branch

docs/admin-manual/troubleshooting.md
=> docs: update apache log filepath

docs/releases/unreleased.md, install, legacy/install/logrotate/libretime-legacy.conf, playout/install/logrotate/libretime-liquidsoap.conf, playout/libretime_playout/notify/main.py, shared/libretime_shared/logging.py
=> feat: improve logging

installer/vagrant/debian.sh
- add vim package
- split apt-cacher packages and utils
=> chore: improve vagrant debian prepare script

docs/admin-manual/setup/install.md, website/versioned_docs/version-3.0.0-alpha.12/admin-manual/setup/install.md
=> docs: explicitly mention lack of 22.04 support

docs/releases/unreleased.md
=> docs: add missing storage config upgrade procedure

docs/admin-manual/setup/install.md, website/versioned_docs/version-3.0.0-alpha.12/admin-manual/setup/install.md
=> docs: remove packages based install

.github/workflows/housekeeping.yml, docs/releases/3.0.0-alpha.08.md, website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.08.md
=> ci: replace link checker report with failing job

.github/workflows/api-schema.yml, .pre-commit-config.yaml, api/Makefile, api/schema.yml
The commits are all pushed separately to trigger a workflow on the remote repository.
=> ci: check if api schema is outdated for all commits

.github/workflows/_python.yml, .github/workflows/api.yml
=> ci: fix python packages caching

.github/workflows/api-schema.yml
=> ci: fix schema update commit author

api/Makefile, api/pyproject.toml, codecov.yml, tools/python.mk
@paddatrapper I hope this fixes everything.
Fixes #1927
=> ci: tweak coverage

codecov.yml
We don't have test coverage requirements yet
=> ci: disable codecov patch status check

docs/admin-manual/uninstall.md
Help those previously relying on the uninstall script and that cannot have disposable system to install LibreTime.
=> docs: provide uninstall guidance

analyzer/README.md, analyzer/install/systemd/libretime-analyzer.service, api/README.md, api/install/systemd/libretime-api.service, api/install/systemd/libretime-api.socket, api/packages.ini, docs/admin-manual/library.md, docs/admin-manual/setup/install.md, docs/admin-manual/setup/upgrade.md, docs/admin-manual/troubleshooting.md, docs/admin-manual/uninstall.md, docs/releases/unreleased.md, docs/user-manual/playout-history.md, install, installer/nginx/libretime.conf, installer/vagrant/debian.sh, installer/vagrant/post-install.sh, legacy/application/common/CORSHelper.php, legacy/install/php-fpm/libretime-legacy.conf, legacy/packages.ini, playout/install/systemd/libretime-liquidsoap.service, playout/install/systemd/libretime-playout.service, tools/packages_test.py, worker/install/systemd/libretime-celery.service
- Fixes #1186
- Fixes #1637
- Fixes #1719
=> feat: use dedicated 'libretime' user with nginx + php-fpm

Makefile
Always update the VERSION file unless we are in a release tarball.
=> fix(installer): update version file unless tarball

README.md, docs/admin-manual/setup/install.md, docs/developer-manual/development/_category_.yml, docs/developer-manual/development/environment.md, docs/developer-manual/development/releases.md
=> docs: add releases distributions support

analyzer/setup.py, api-client/setup.py, api/setup.py, playout/setup.py, shared/setup.py, worker/setup.py
This should prevent from forgetting to manually add each subpackages
=> chore: use setuptools find_packages

legacy/application/services/PodcastEpisodeService.php, worker/libretime_worker/config.py, worker/libretime_worker/tasks.py
=> feat(worker): load callback details from config

analyzer/libretime_analyzer/config.py, analyzer/libretime_analyzer/main.py, analyzer/libretime_analyzer/message_listener.py, analyzer/libretime_analyzer/pipeline/pipeline.py, analyzer/libretime_analyzer/status_reporter.py, analyzer/tests/pipeline/pipeline_test.py, legacy/application/models/RabbitMq.php, legacy/application/models/airtime/CcFiles.php, legacy/application/services/MediaService.php
=> feat(analyzer): load callback details from config and file_id

api-client/libretime_api_client/_client.py, api-client/tests/client_test.py, api-client/tests/v2_test.py
urljoin really has a complex behavior.
=> fix(api-client): fix base_url joining for client v2

legacy/application/common/FileDataHelper.php, legacy/application/models/StoredFile.php
=> fix(legacy): sanitize track_type_id when updating file

install
This allow to edit deeply nested values in the config file, which will be required for setting the icecast passwords.
=> feat(installer): use ed for config update

docker-compose.yml
Cherry picking few commits from #1471
=> chore: update compose stack

docs/admin-manual/custom-authentication.md, docs/admin-manual/setup/install.md, docs/admin-manual/setup/migrate-from-airtime.md
=> docs: edit timezone during setup

website/package.json, website/yarn.lock
=> chore: upgrade website packages

playout/libretime_playout/liquidsoap/1.3/ls_script.liq, playout/libretime_playout/liquidsoap/1.4/ls_script.liq
=> fix(playout): replace deprecated harbor.bind_addr

playout/libretime_playout/liquidsoap/entrypoint.py, playout/libretime_playout/main.py, playout/libretime_playout/message_handler.py, playout/libretime_playout/player/fetch.py, playout/libretime_playout/player/file.py, playout/libretime_playout/player/liquidsoap.py, playout/libretime_playout/player/liquidsoap_gateway.py, playout/libretime_playout/player/push.py, playout/libretime_playout/player/queue.py, playout/libretime_playout/recorder.py, playout/libretime_playout/stats.py
Mainly exception handling improvements
=> refactor(playout): improve exceptions handling

tools/python.mk
=> chore: pin setuptools to <64.0.0 for development

analyzer/pyproject.toml, api-client/pyproject.toml, api/pyproject.toml, playout/pyproject.toml, shared/pyproject.toml, tools/pyproject.toml, worker/pyproject.toml
=> chore: pin setuptools to <64.0.0 for build backend

playout/libretime_playout/player/file.py
=> fix(playout): use stream download when fetching files

docs/releases/unreleased.md
=> docs: add distro releases deprecation notice

docs/admin-manual/setup/configuration.md, installer/config.yml
Cherry picking some changes from #1986
=> docs: improve configuration comments

legacy/application/configs/conf.php, legacy/application/controllers/ListenerstatController.php, legacy/tests/phpunit.xml
Cherry picking some changes from https://github.com/libretime/libretime/pull/1986
=> fix(legacy): small fixes

legacy/application/configs/conf.php
=> fix(legacy): look in /legacy for a VERSION file

.github/workflows/docs.yml, .github/workflows/housekeeping.yml, .github/workflows/project.yml
=> ci: reduce api calls

api/libretime_api/schedule/models/show.py, api/libretime_api/schedule/serializers/show.py, api/libretime_api/schedule/tests/models/test_show.py, api/schema.yml, playout/libretime_playout/player/schedule.py, playout/tests/player/schedule_test.py
=> fix(playout): missing live show events

api/libretime_api/urls.py, installer/nginx/libretime.conf
=> feat(api): move /api-auth to /api/browser

.github/renovate.json
=> ci: fix docusaurus monorepo config

legacy/application/models/StoredFile.php
=> fix(legacy): track_type_id should cast to int not text

.github/renovate.json, website/package.json, website/yarn.lock
=> chore: update renovate config

.github/workflows/actions/build-container/action.yml, .github/workflows/container.yml, Dockerfile
=> ci: improve containers build caching

legacy/application/check.php, legacy/application/configs/config-check.php, legacy/application/views/scripts/systemstatus/index.phtml
Remove external services checks when missing systemctl (mainly in container setup).
=> feat(legacy): disable services check when missing systemctl

docker-compose.yml
=> feat: use libretime/icecast container image

legacy/application/assets.json, legacy/public/js/airtime/library/library.js
=> fix(legacy): number of tracks displayed initially

legacy/application/models/StoredFile.php, legacy/application/services/MediaService.php
=> fix(legacy): prepend file id in tmp upload filename

legacy/application/common/FileDataHelper.php, legacy/application/controllers/plugins/PageLayoutInitPlugin.php, legacy/application/models/airtime/CcFiles.php
=> fix(legacy): fail when uploading wma files

website/blog/2022-09-17-libretime-v3-beta.0.md, website/blog/authors.yml, website/docusaurus.config.js
@paddatrapper Feel free to write or dump ideas in the blog post.
This should be merged once we release beta.0, I am already starting to write it now so we have time to dump all our thoughts and correct everything.
I think this will be a good way to get more testing and prepare people for a coming v3 release.
We will be able to explain what happen in the past months, what didn't happen and what should happen in the future.
=> docs: first blog post, v3 beta.0

.github/workflows/actions/build-container/action.yml, .github/workflows/container.yml, Dockerfile, legacy/application/configs/conf.php, tools/version.sh
=> fix: include version variable inside containers

tools/icecast-stress.sh
Unsure if this belongs here. Should we create a community repo ? For scripts and helpers ?
=> chore: add icecast stress script

legacy/application/controllers/DashboardController.php, legacy/application/layouts/scripts/livestream.phtml, legacy/application/views/scripts/dashboard/stream-player.phtml
=> fix(legacy): add play button to stream player

analyzer/install/systemd/libretime-analyzer.service, api/install/systemd/libretime-api.service, playout/install/systemd/libretime-liquidsoap.service, playout/install/systemd/libretime-playout.service, worker/install/systemd/libretime-worker.service
Second batch off isolation settings.
=> feat: extra systemd service hardening

docs/admin-manual/troubleshooting.md, tools/test-stream-input.py
This helps sending a sine wave sound to the input harbor for testing purpose. I know ffmpeg more reliable than butt or mixx.
=> chore: add test-stream-input tool 

install
=> fix: disable some systemd security features on bionic

.pre-commit-config.yaml, analyzer/libretime_analyzer/pipeline/_utils.py, analyzer/libretime_analyzer/pipeline/pipeline.py, playout/libretime_playout/config.py, playout/libretime_playout/liquidsoap/client/_client.py, playout/libretime_playout/liquidsoap/version.py, playout/libretime_playout/main.py, playout/libretime_playout/message_handler.py, playout/libretime_playout/player/fetch.py, playout/libretime_playout/player/file.py, playout/libretime_playout/player/push.py, playout/libretime_playout/player/queue.py, playout/tests/liquidsoap/client/connection_test.py, shared/libretime_shared/config/_models.py
=> refactor: upgrade code to Python 3.8

api/libretime_api/legacy/migrations/0043_remove_cors_preference.py, api/libretime_api/legacy/migrations/__init__.py, legacy/application/common/CORSHelper.php, legacy/application/controllers/PreferenceController.php, legacy/application/forms/GeneralPreferences.php, legacy/application/models/Preference.php, legacy/application/views/scripts/form/preferences_general.phtml
- Remove after deprecation in eb8e7b3415c77c9274e4465f68d19857be940c06
=> feat(legacy): remove db allowed_cors_origins preference

playout/tests/liquidsoap/version_test.py
The PPA was previously not properly installed in the dev container.
Partial cherry-pick from 499f4d37edf46ff408e4cf23eda35b331821ab96
=> test: liquidsoap package from ppa is version 1.4.2

analyzer/install/systemd/libretime-analyzer.service, api/install/systemd/libretime-api.service, playout/install/systemd/libretime-liquidsoap.service, playout/install/systemd/libretime-playout.service, worker/install/systemd/libretime-worker.service
=> fix: remove systemd ProtectHome feature

Dockerfile
This reverts commit d2d4ebdf8263d495232a0597a7c896bbaf0dbd9e.
=> fix(deps): revert update python docker tag to v3.11 (#2245)

Dockerfile
- merge RUN calls together
- add `set -eux`
=> chore: improve dockerfile run calls

install
Remove warnings if the current dir is not writable by postgres
=> fix(installer): set home and login when running as postgres

legacy/application/check.php, legacy/application/preload.php
Prevent blank pages or unexpected errors when checking the services connection.
=> fix(legacy): log errors on connect check failure

worker/libretime_worker/tasks.py
Backport for dbf4667bd878230fee67b70bd8b519feed6746f3
=> fix(worker): replace deprecated cgi.parse_header

.github/workflows/docs.yml, analyzer/setup.py, api-client/setup.py, api/setup.py, docs/developer-manual/development/releases.md, docs/releases/3.0.1.md, playout/setup.py, shared/setup.py, worker/setup.py
Merging the 3.0.x branch in main.
=> chore: merge 3.0.x into main

legacy/composer.json, legacy/composer.lock, legacy/tests/application/bootstrap.php
=> fix(legacy): move forked deps to the libretime namespace

.pre-commit-config.yaml, analyzer/pyproject.toml, api-client/pyproject.toml, api/pyproject.toml, playout/pyproject.toml, pyproject.toml, shared/pyproject.toml, worker/pyproject.toml
=> chore: add isort pre-commit hook

docs/admin-manual/setup/install.md, install
Fixes #2338
@paddatrapper What do you think about this change ? Does it adds to much complexity ?
=> fix(installer): only setup nginx on first install

.github/workflows/api-schema.yml, .pre-commit-config.yaml, analyzer/libretime_analyzer/message_listener.py, analyzer/libretime_analyzer/pipeline/__init__.py, analyzer/libretime_analyzer/pipeline/analyze_cuepoint.py, analyzer/libretime_analyzer/pipeline/pipeline.py, analyzer/tests/pipeline/analyze_cuepoint_test.py, analyzer/tests/pipeline/pipeline_test.py, api/libretime_api/legacy/migrations/0044_add_track_types_analyzer_options.py, api/libretime_api/legacy/migrations/__init__.py, api/libretime_api/legacy/migrations/sql/schema.sql, api/libretime_api/storage/models/library.py, api/schema.yml, legacy/application/assets.json, legacy/application/controllers/TracktypeController.php, legacy/application/forms/AddTracktype.php, legacy/application/models/RabbitMq.php, legacy/application/models/Tracktype.php, legacy/application/models/airtime/CcFiles.php, legacy/application/models/airtime/map/CcTracktypesTableMap.php, legacy/application/models/airtime/om/BaseCcTracktypes.php, legacy/application/models/airtime/om/BaseCcTracktypesPeer.php, legacy/application/models/airtime/om/BaseCcTracktypesQuery.php, legacy/application/services/MediaService.php, legacy/build/schema.xml, legacy/public/js/airtime/tracktype/tracktype.js, tools/legacy-migrations-version.sh
Fix #1818
~~I am not happy with how I implemented this. But I guess I don't want to play too much with PHP...~~
The disable cuepoint_analyze option should go in track_type table as field, but I was a bit lazy going that route as used the preference table.
=> feat: allow disabling cuepoint analysis per track type

analyzer/setup.py, api-client/setup.py, api/setup.py, docs/releases/3.0.2.md, playout/setup.py, shared/setup.py, worker/setup.py
I would like to release another patch version.
I am only waiting for:
- #2379 
- #2381
=> chore: release 3.0.2

docker/config.dev.yml, playout/libretime_playout/liquidsoap/1.4/ls_lib.liq, playout/libretime_playout/liquidsoap/1.4/ls_script.liq, playout/libretime_playout/liquidsoap/client/_client.py, playout/libretime_playout/liquidsoap/entrypoint.liq.j2, playout/libretime_playout/liquidsoap/entrypoint.py, playout/libretime_playout/liquidsoap/utils.py, playout/tests/liquidsoap/__snapshots__/entrypoint_test.ambr, playout/tests/liquidsoap/utils_test.py
=> feat(playout): use liquidsoap interactive variables

.gitignore, docker-compose.override.yml, playout/libretime_playout/liquidsoap/1.4/ls_lib.liq, playout/libretime_playout/liquidsoap/1.4/ls_script.liq, playout/libretime_playout/liquidsoap/client/_client.py, playout/libretime_playout/liquidsoap/entrypoint.liq.j2, playout/libretime_playout/player/fetch.py, playout/libretime_playout/player/liquidsoap.py, playout/tests/liquidsoap/__snapshots__/entrypoint_test.ambr
- rename some variables to be consistent with the config keys
- rename some non obvious variables names
- remove dead code (mainly related to the now unused "restart liquidsoap after settings change" feature)
=> refactor(playout): remove unused code and improve code quality

CONTRIBUTING.md, docs/developer-manual/development/releases.md
=> docs: adapt c4 to our workflows

tools/Makefile, tools/contibutors.py
Yet another contributors listing script, sorry...
=> chore: add contributors listing tool

.pre-commit-config.yaml, Dockerfile, analyzer/Makefile, analyzer/libretime_analyzer/__init__.py, analyzer/libretime_analyzer/main.py, analyzer/setup.py, api-client/libretime_api_client/__init__.py, api/Makefile, api/libretime_api/__init__.py, api/libretime_api/settings/_internal.py, api/setup.py, playout/Makefile, playout/libretime_playout/__init__.py, playout/libretime_playout/main.py, playout/setup.py, shared/libretime_shared/__init__.py, worker/Makefile, worker/libretime_worker/__init__.py, worker/libretime_worker/tasks.py, worker/setup.py
=> feat: add sentry sdk

playout/libretime_playout/main.py, playout/libretime_playout/message_handler.py, playout/libretime_playout/player/fetch.py, playout/libretime_playout/player/file.py, playout/libretime_playout/player/push.py, playout/libretime_playout/player/queue.py, playout/tests/message_handler_test.py, playout/tests/player/fetch_test.py, playout/tests/player/file_test.py, playout/tests/player/liquidsoap_test.py, playout/tests/player/push_test.py, playout/tests/player/queue_test.py
=> test(playout): class creation

docker/config.template.yml, docs/admin-manual/install/install-using-docker.md, tools/update-config-files.sh
=> docs: docker config template install with envsubst

dev/config.yml, docker-compose.override.yml, docker/config.template.yml, docker/config.yml, docker/example/config.yml, docs/admin-manual/configuration.md, docs/admin-manual/install/install-using-the-installer.md, installer/config.yml, legacy/application/configs/conf.php, legacy/application/models/Preference.php, legacy/application/models/StreamSetting.php, playout/libretime_playout/config.py, playout/libretime_playout/liquidsoap/1.4/ls_script.liq, playout/libretime_playout/liquidsoap/templates/entrypoint.liq.j2, playout/tests/liquidsoap/__snapshots__/entrypoint_test.ambr, playout/tests/liquidsoap/fixtures/__init__.py, shared/libretime_shared/config/_models.py
=> feat(playout): allow secure input harbor configuration

Dockerfile, analyzer/packages.ini, api/install/systemd/libretime-api.service, api/packages.ini, api/requirements.txt, api/setup.py, install, worker/install/systemd/libretime-worker.service
=> feat: install libretime inside a venv

docs/admin-manual/install/migrate-from-airtime.md
=> docs: improve airtime migration guide

Dockerfile, api/requirements.txt, api/setup.py
=> chore(deps): update dependency djangorestframework to >=3.14.0,<3.15

api/libretime_api/settings/_schema.py, api/libretime_api/settings/prod.py, api/libretime_api/settings/testing.py, dev/config.yml, docker-compose.override.yml, docker/config.template.yml, docker/config.yml, docker/example/config.yml, docs/admin-manual/configuration.md, installer/config.yml, legacy/application/configs/conf.php
Related to #724 it will be fixed once we move the authentication/password reset to Django
=> feat(api): add email configuration

docker-compose.yml
Back porting #2615 into stable. We made the mistake to merge it in the main branch.
=> fix: libretime process leaks and lsof high cpu usage (#2615)

.github/renovate.json
- Make it more silent
- Auto merge any Github Action or Pre-commit version change.
- Auto merge lock file updates.
=> chore: improve renovate auto merge

.codespellignore, analyzer/setup.py, api-client/setup.py, api/setup.py, docs/releases/3.2.0.md, playout/setup.py, shared/setup.py, worker/setup.py
=> chore: release 3.2.0 

tools/python.mk
=> chore: remove pylint install workaround

.github/workflows/container.yml
Supersedes:
- https://github.com/libretime/libretime/pull/2809
- https://github.com/libretime/libretime/pull/2815
=> ci: update actions/*-artifact actions to v4

.github/workflows/backport.yml
Better integrations with release-please, using my action fork until https://github.com/tibdex/backport/pull/109 is merged upstream.
=> ci: update backport bot templates

.github/workflows/pr.yml
Ensure the release pull request does not fail the PR title check.
=> ci: add branch names to commit scopes

api/libretime_api/core/tests/models/test_preference.py, api/libretime_api/core/views/info.py, api/libretime_api/core/views/stream.py
Fix some deprecation warnings related to the pydantic upgrade.
=> refactor(api): fix deprecation warnings

api/libretime_api/settings/prod.py, docker/config.template.yml, docker/config.yml, docker/example/config.yml, docs/admin-manual/configuration.md, docs/releases/unreleased.md, installer/config.yml, legacy/application/configs/conf.php, playout/tests/conftest.py, playout/tests/liquidsoap/fixtures/__init__.py, shared/libretime_shared/config/_models.py, shared/tests/config/models_test.py
BREAKING CHANGE: The `general.secret_key` configuration field is now required. Make sure to update your configuration file and add a secret key.
Closes #2426
=> feat!: the `general.secret_key` configuration field is now required

worker/tests/conftest.py
Missing secret_key change from https://github.com/libretime/libretime/pull/2841
=> refactor(worker): add require secret_key config field

cloud-init.yml
Fix and update the could init config to install an insecure LibreTime server.
=> feat: rewrite cloud-init config

analyzer/install/systemd/libretime-analyzer.service, api/install/systemd/libretime-api.service, playout/install/systemd/libretime-liquidsoap.service, playout/install/systemd/libretime-playout.service, worker/install/systemd/libretime-worker.service
Set PYTHONOPTIMIZE=2 to enable https://docs.python.org/3/using/cmdline.html#cmdoption-OO
=> feat: run python in optimized mode

.github/renovate.json, .github/workflows/analyzer.yml, .github/workflows/api-client.yml, .github/workflows/api.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/legacy.yml, .github/workflows/playout.yml, .github/workflows/project.yml, .github/workflows/shared.yml, .github/workflows/worker.yml, docs/contribute.md, docs/contributor-manual/development-workflows.md, docs/contributor-manual/releases.md, docs/releases/README.md
Related to https://github.com/libretime/libretime/issues/2887
=> chore: introduce the stable-4.x branch

docs/admin-manual/stream-configuration.md, docs/admin-manual/tutorials/setup-liquidsoap-aac-streaming.md
Documentation update regarding #2184
=> docs(playout): add a tutorial to enable AAC in liquidsoap

docs/admin-manual/tutorials/setup-liquidsoap-aac-streaming.md
=> docs: fix broken link to install guide

.vale.ini, docs/user-manual/settings.md
Minor broken link, preventing website from building
=> docs: fix broken link

.vale.ini
=> chore: reenable vale rule after fix

docs/admin-manual/custom-authentication.md
Minor typo that was being picked up by pre-commit
=> docs: fix typo

.github/workflows/housekeeping.yml, README.md
Only show organizations avatars.
=> chore: fix broken link check

legacy/application/controllers/LoginController.php
The file is non existent.
Added in c669d3cb47a3092ac27fb3995f0dc72955f0740d
Removed in ea2a6b3f68c59d98986b6d3f4c9b70137366990f
=> refactor: remove non existent asset file

docs/admin-manual/install/install-using-docker.md
Improve the Docker install documentation, along with the `docker compose` commands.
=> docs: use new docker compose command

legacy/application/models/Block.php
The filename criteria searched the full file path and as such does not work as expected.
No
No docs changes are required as this is fixing a bug to make things work as expected and documented.
I uploaded some files, and tested that the file name criteria worked as expected.
Spin up the stack, upload some files and make sure the filename criteria works as expected.
=> fix(legacy): fix filename criteria searching

docs/appendix/rights-royalties.md
updated the minimum SoundExchange royalties for non-profits/non-commercial
_Short summary of what is the issue and the solution._
_Do the changes in this PR implement a new feature?_
_Are there documentation changes required as a result of these changes? See
https://github.com/libretime/libretime/wiki/Documentation-Requirements_
_What did you do to validate this PR?_
_How can the reviewer validate this PR?_
_Issues links or other related resources. Use the line Closes: #bug_number to
link a bug in the issue tracker._
=> docs: update SoundExchange costs

legacy/public/js/datatables/i18n/nb_NO.txt
=> fix: add missing file for nb_NO locale

api/libretime_api/core/models/user.py, playout/libretime_playout/player/fetch.py
The name and condition has changed
=> chore: fix linting ignore comments

api/setup.py
Upstream has fixed the issue.
Closes: #3064
=> chore: update django-stubs version

legacy/application/models/Block.php
When running a radio station it is generally a good idea to reduce dead air time. The current algorithm for adding tracks to a block/show can leave a lot of dead air time at the end as it doesn't use a very good algorithm. Adding tracks to a show until it is full while making it as full as possible is a well known problem in computer science. It is the [Subset Sum Problem](https://en.wikipedia.org/wiki/Subset_sum_problem). This PR implements a Randomized Greedy with Local Improvement (RGLI) approximation solution for the Subset Sum Problem. The new algorithm is only used when sort type is random and overflow is not enabled and there is no limit on the number of tracks that can be used.
Improvement on an existing feature. 
**I have not updated the documentation …
=> feat(legacy): implement subset sum solution to show scheduling

legacy/application/models/Block.php, legacy/application/models/StoredFile.php
=> fix(legacy): support Postgresql 12 syntax

api/libretime_api/mixins/__init__.py, api/libretime_api/mixins/readwriteserializer.py, api/libretime_api/schedule/serializers/__init__.py, api/libretime_api/schedule/serializers/schedule.py, api/libretime_api/schedule/views/schedule.py, api/schema.yml
=> feat(api): enable writes to schedule table

.github/workflows/legacy.yml
=> ci: make libretime test user owner of test database

Makefile, docs/contributor-manual/development-environment.md
Upstream has renamed docker-compose to docker compose for all commands
_Do the changes in this PR implement a new feature?_
Yes
=> chore: update docker compose commands

.github/workflows/_python.yml, .github/workflows/housekeeping.yml, .github/workflows/project.yml
=> ci: fix failures

docs/admin-manual/install/install-using-docker.mdx, docs/admin-manual/install/install-using-the-installer.mdx, docs/releases/3.0.0-alpha.00.mdx, docs/releases/3.0.0-alpha.01.mdx, docs/releases/3.0.0-alpha.02.mdx, docs/releases/3.0.0-alpha.03.mdx, docs/releases/3.0.0-alpha.04.mdx, docs/releases/3.0.0-alpha.05.mdx, docs/releases/3.0.0-alpha.06.mdx, docs/releases/3.0.0-alpha.07.mdx, docs/releases/3.0.0-alpha.08.mdx, docs/releases/3.0.0-alpha.09.mdx, docs/releases/3.0.0-alpha.10.mdx, docs/releases/3.0.0-alpha.11.mdx, docs/releases/3.0.0-alpha.12.mdx, docs/releases/3.0.0-alpha.13.mdx, docs/releases/3.0.0-beta.0.mdx, docs/releases/3.0.0-beta.1.mdx, docs/releases/3.0.0-beta.2.mdx, docs/releases/3.0.0.mdx, docs/releases/3.0.1.mdx, docs/releases/3.0.2.mdx, docs/releases/3.1.0.mdx, docs/releases/3.2.0.mdx, docs/releases/4.0.0.mdx, docs/releases/4.1.0.mdx, docs/releases/4.2.0.mdx, docs/releases/4.3.0.mdx, docs/releases/_release-head.mdx, docs/releases/unreleased.mdx
V3 has several breaking changes that need to be addressed
Tested using docusaurus:
```shell
make docs-dev
```
=> docs: prepare docs for Docusaurus v3

.github/workflows/docs.yml, .vale.ini
=> ci: update vale to support MDX

docs/releases/4.3.0.mdx
See https://github.com/libretime/libretime/issues/3150
=> docs: note #3150 docker volume deletion required in upgrade
