libretime/libretime

airtime_mvc/application/configs/constants.php
airtime_mvc/application/controllers/LoginController.php

Solution: Make the login fallback optional and deactivate it in the default config.
I'm leaving the code in here mostly because I want to revisit it and make it modular so I can later on plug my own FreeIPA things :)

Problem: Failed logins always try log in against legacy upstream

---

airtime_mvc/application/configs/constants.php
airtime_mvc/application/controllers/plugins/PageLayoutInitPlugin.php

Problem: Live Chat points back to legacy upstream and I do not believe we can let them do support for us ;)
Solution: Deactivate live chat through constants.php so it never gets checked.
This is like https://github.com/Robbt/Airtime/commit/34db703381f8ccf7fdee3706c3df58f347da7e00 but removes one more sql call and makes it easy to reactivate should anyone want to use the feature in future.

config to disable live chat

---

airtime_mvc/application/controllers/PlaylistController.php

Was on 2.5.x as 7dbf4cf5d2d37057e1f5ab72cb12ffcc5ddc1ccb

Add missing argument to playlistNotFound call

---

airtime_mvc/application/configs/constants.php
airtime_mvc/application/models/RabbitMq.php
airtime_mvc/public/setup/media-setup.php
python_apps/airtime-celery/README.rst
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader.py
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py
python_apps/airtime_analyzer/bin/airtime_analyzer
python_apps/airtime_analyzer/tests/analyzer_pipeline_tests.py

This is the results of 
```bash
sed -i -e 's|/etc/airtime-saas/|/etc/airtime/|' `grep -irl 'airtime-saas' airtime_mvc/ python_apps/` 
```
It might need more testing, the airtime-saas part never really made sense, zf1 has environments for that, ie you would create a saas env based on production for instance.
I beleive legacy upstream was using this to share configuration between customers (ie. analyser runs only once and writes to a shared S3 bucket). I assume they mount the airtime-saas folder onto individual customers instances with a global config. Like I said, I don't feel that this makes sense since all it does is make hacking at the configs in airtime-saas a bit easier. A serious SaaS operation should be using something like puppet or ansible to achieve this.

Rewrite config from /etc/airtime-saas to plain /etc/airtime

---

airtime_mvc/application/models/airtime/CcFiles.php
airtime_mvc/application/modules/rest/controllers/MediaController.php

This should give us more information in the case of an error and is the framework idiomatic way to handle a RESTful file upload.
I'm hoping this helps debug https://github.com/LibreTime/libretime/issues/3

Use Zend_File_Transfer instead of $_FILES

---

Vagrantfile
docs/_css/term.css
docs/documentation.md
docs/features.md
docs/index.md
docs/install.md
docs/scripts/install.sh
docs/scripts/serve.sh
mkdocs.yml

Since the installation script appears not to be functioning at the moment, I figured adding a Vagrantfile would make for simpler local dev/test environment setup and teardown.
I've currently got our docs being built and served via Mkdocs within the Vagrant VM, to simplify documentation. I figure to add provisioning via our install script, so that we end up with a full-functioning LibreTime install.

Add Vagrant support

---

airtime_mvc/application/forms/StreamSetting.php
install

This re-adds hardware output setting in the ui as per the [taiga#29](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork/issue/29).
It's basically a cherry-pick of only the first commit from #40. Most of the install issues from #40 have already been sorted out and other issues have open PRs. We will do a 3.0.0-alpha release as soon has we have feature-parity with the tarball (assumingly where most of @comiconomenclaturist's changes came from).
Fixes #40
Thanks, @comiconomenclaturist for the contribution.

Re-enable hw output

---

airtime_mvc/build/airtime.example.conf

This will get rid of the sad tape error on the facebook widgets page `/embeddablewidgets/facebook`. We will probably end up having to document how to set up facebook properly, but I'd like to take care of that while I'm testing against real facebook.

Add empty default Facebook config

---

build.sh

Currently the installer fails when using a github tarball that comes without a .git folder (https://github.com/LibreTime/libretime/issues/47#issuecomment-285365745).
With this change build.sh only executes git if a .git folder is detected. It uses the name of the downloaded folder as part of the version string if a tarball is used.
I plan on releasing travis-ci built tarballs that contain the tagged version (once we have one) and also have a pre-downloaded composer vendor folder. Those will already contain a VERSION file as well and this change already contains the setup needed for that.
Example output with `.git/` folder without tag
```
* Building from Git
* Version from tag: 
* Overriding empty version with sha1 commit-ish: 285ed854f
```
With tag:
```
* Building from Git
* Version from …
```

Make git optional during build

---

airtime_mvc/build/rabbitmq-analyzer.ini

This fixes #24 by adding a rabbitmq-analyzer.ini file.

adding the default rabbitmq-analyzer.ini file to fix install script

---

airtime_mvc/application/common/CORSHelper.php
airtime_mvc/application/controllers/ApiController.php
airtime_mvc/application/controllers/LoginController.php
airtime_mvc/application/controllers/PreferenceController.php
airtime_mvc/application/forms/GeneralPreferences.php
airtime_mvc/application/models/Preference.php
airtime_mvc/application/views/scripts/form/preferences_general.phtml

This fixes CORS to work properly with most 2.5 api endpoints while keeping the JSONP format available.
See #17 for what triggered this refactor. I believe this should make integrating the APIs on the client side trivial without mandating the use of JSONP.
Response headers as seen with [test-cors.org](http://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Flocalhost%3A9080%2Fapi%2Flive-info&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) (visible in browser dev tools):
```
Access-Control-Allow-Origin: http://www.test-cors.org
```
There is no such header when making direct requests.

Make CORS great again

---

airtime_mvc/application/forms/StreamSetting.php

Let's just call this "default" streaming for now. Fixes #31

Replace Airtime Pro wording

---

airtime_mvc/application/views/scripts/embed/player.phtml
airtime_mvc/application/views/scripts/embed/weekly-program.phtml

Solution: Use PRODUCT_NAME and PRODUCT_SITE_URL in pro widgets.

Problem: Pro widgets contain ads for legacy upstream

---

Vagrantfile
install
installer/vagrant/centos.sh
python_apps/pypo/liquidsoap/ls_script.liq

These are the remaining blocker issues we found when retesting CentOS with #64.

Problem: Install cleanup needed for CentOS

---

airtime_mvc/application/models/Block.php

this fixes #73 - it doesn't apply an optimal search algorithm to make tracks meet the length, it just doesn't add tracks that would exceed the time length, and cycles through up to 500 tracks adding items it can without exceeding the time length.

modified smart block to not exceed the time limits.

---

python_apps/pypo/bin/pyponotify
python_apps/pypo/pypo/__main__.py
python_apps/pypo/pypo/pypofetch.py
python_apps/pypo/pypo/pypofile.py
python_apps/pypo/pypo/pypomessagehandler.py
python_apps/pypo/pypo/pypopush.py

Solution: Replace std_err_override with logging.captureWarnings(True) in pypo
The quite ugly hack with std_err_override seems to have been made for python < 2.7. Since all major distros have at least python 2.7 installed we can stop using the std_err_override hack.
This removes it from pypo, media-monitor still uses the module and we can completely delete it when we have removed media-monitor after having maybe backported the watched folders feature to analyzer.
I'm doing this since it makes packaging pypo much easier, we have one module less to care about. I'm also considering putting the modules we end up keeping into the [Python Package Index](https://pypi.python.org/pypi) index so we do not need a local clone or tarball to install python parts.

Problem: std_err_override is a hack for python < 2.7

---

airtime_mvc/application/common/GoogleAnalytics.php
airtime_mvc/application/configs/constants.php
airtime_mvc/application/controllers/plugins/PageLayoutInitPlugin.php
airtime_mvc/application/layouts/scripts/layout.phtml
airtime_mvc/public/js/libs/google-analytics.js

My browser was already blocking this. I feel we should not tag a release that uses google services with any ids relating to legacy upstream.

Disable all google tracking per default

---

installer/vagrant/centos.sh

Pypo uses lsof to check if files are not being used before removing them. This one was a bit non obvious since it errs to the log and doesn't affect playout.

Add missing playout dependency

---

airtime_mvc/application/configs/constants.php
airtime_mvc/application/models/Email.php

The new noreply@ address is now `noreply@libretime.org` and the address gets moved to contants.php rather than being hardcoded in the email model.
Fixes #18

Change default email sender

---

airtime_mvc/application/controllers/LoginController.php
airtime_mvc/application/forms/PasswordRestore.php
airtime_mvc/application/models/Auth.php
airtime_mvc/application/views/scripts/form/password-restore.phtml

This stops distinguishing between superadmin users from whmcs vs regular local users on the password reset page.
Sending mail gets handled through `mail()` so it is up to the sysadmin to set this up properly. The vagrant install is not able to send mail out of the box and I think that is ok.
Fixes #12

Make password reset work for eveyone

---

README.md
docs/faq.md
docs/translating.md
mkdocs.yml

I linked these docs from the help page pointing to a 404 and this takes care of adding some rather bare content so we have something up and running for 3.0.0-alpha.
I believe this is about all we need for the first release. It can also be merged post-release since it will show up on the docs instantly.
I'll tag 3.0.0-alpha release later today and do some more outreach after it is tagged. I'd also like to start draining the taiga board to ensure that nothing went missing from there.

Add docs linked from help page

---

dev_tools/release/release.sh

Make it add vendor to the tarball and just be a generally nicer script with less verbose output and no ability to wipe my working copies .git folder when executed in the wrong dir.
I plan on using this to create tarballs that can be used for the rpmbuild process without the build box needing to run composer and connect to the internet. The openSUSE Build Service boxen do not have a connection to the internet during builds.
I'll do some additional testing with travis and my fork before I implement the changes needed for travis to autodeploy the tarball built by the script. For 3.0.0-alpha I'll probably just upload the results of the script.

Fix release.sh script

---

airtime_mvc/application/controllers/PreferenceController.php
airtime_mvc/application/forms/GeneralPreferences.php
airtime_mvc/application/models/Preference.php
airtime_mvc/application/services/PodcastEpisodeService.php
airtime_mvc/application/views/scripts/form/preferences_general.phtml
python_apps/airtime-celery/airtime-celery/tasks.py

This adds an option to preferences that makes it so that downloaded podcasts will always have their album ID3 tag  overridden, even if it isn't empty. 
There needs to be some troubleshooting because it is always overriding even if this option is disabled. 
This is either due to the wrong boolean being passed via rabbitMQ to the celery task or the python code in the celery tasks.py not being able to interpret the bool correctly. I'll work to fix it but if someone else notices a possible issue feel free to point it out. 
This fixes #89

basic podcast album override option in preferences

---

airtime_mvc/application/models/StoredFile.php
python_apps/api_clients/api_clients/api_client.py

This is an old one from my legacy upstream fork and takes care of allowing the api client to access files from the library through tls if the tls listener is on port 443.
It also has a fix for the API where it would build a `https://<hostname>:80` url instead of `https://<hostname>:443`. A more serious fix would probably make the URL configurable on not depend on `$_SERVER` as much, but this works.
For it to also work we would need to make the protocol fully configurable. At least with this things won't completely fail if you switch the install to 443 and close off 80.

General fixes for TLS

---

installer/systemd/airtime-celery.service
installer/systemd/airtime-liquidsoap.service
installer/systemd/airtime-playout.service
installer/systemd/airtime_analyzer.service

This essentially results in the same behaviour legacy upstream was exploiting in upstart. Normally I would argue that depending on such a feature as part of an applications runtime feature-set is bad. This applies, but until we can get that sorted at another level this makes everything work as intended when running through systemd.

Restart services always with systemd

---

airtime_mvc/application/controllers/downgrade_sql/airtime_3.0.0-alpha.1/downgrade.sql
airtime_mvc/application/controllers/upgrade_sql/airtime_3.0.0-alpha.1/upgrade.sql
airtime_mvc/application/models/airtime/map/ImportedPodcastTableMap.php
airtime_mvc/application/models/airtime/map/ThirdPartyTrackReferencesTableMap.php
airtime_mvc/application/models/airtime/om/BaseImportedPodcast.php
airtime_mvc/application/models/airtime/om/BaseImportedPodcastPeer.php
airtime_mvc/application/models/airtime/om/BaseImportedPodcastQuery.php
airtime_mvc/application/models/airtime/om/BaseThirdPartyTrackReferences.php
airtime_mvc/application/services/PodcastEpisodeService.php
airtime_mvc/application/upgrade/Upgrades.php
airtime_mvc/application/views/scripts/podcast/podcast.phtml
airtime_mvc/build/schema.xml
airtime_mvc/build/sql/schema.sql
airtime_mvc/public/css/styles.css

This allows you to override the album name in a downloaded podcast at the per podcast level. The global option takes precedence to it so it can only activate overriding if that is disabled. I should probably change that to it only being used as the default for new podcasts. Let me know what you think.
It also has the fix for getting a green checkmark after downloads have processed.
Setting it results in
vs.
Fixed #92

per podcast album override

---

.travis.yml
dev_tools/release/release.sh
travis/release.sh

This should take care of automatically uploading a release tarball containing a prepoulatated `vendor/` dir as well as a pre-made `VERSION` file to [github releases](https://github.com/LibreTime/libretime/releases).
It tested it as best as I can and I hope that it works as intended on the next tag. If it doesn't I'll prepare a prompt fix. I hope we can get this working without too many tags but think we should just do releases often enough until this works fine.
Based on the same tarball (manually uploaded) from the script I have rpmbuilding pretty much ready on the code side of things, with this I can make it really automated.

Create release tarball using travis

---

airtime_mvc/application/configs/constants.php
airtime_mvc/application/controllers/LocaleController.php
airtime_mvc/application/models/Preference.php
airtime_mvc/application/views/helpers/VersionNotify.php
airtime_mvc/public/css/styles.css
airtime_mvc/public/js/airtime/dashboard/versiontooltip.js
composer.json
composer.lock

This makes LibreTime check its version against github releases and lets the user know when to update. It uses the red exclamation point when there is a patch release or if LibreTime is more than one major release ahead. The orange icon is used when LibreTime is on a git install, a single major update is available, or a pre-release version is installed. The green update icon gets used to signify that a new minor release is available. Finally the green checkmark will be used when you are on a stable release.
It might display some slightly incorrect info while we only have pre-release packages but should work fine afterward. You'll have to run `composer install` after switching the branch since it installs some the version comparing code used.
The actual version check should only get …

Re-implement version check

---

airtime_mvc/application/common/AutoPlaylistManager.php
airtime_mvc/application/models/Scheduler.php
airtime_mvc/application/models/ShowInstance.php

The add playlistoshow function had a parameter that wasn't being utilized to allow it to tell the validation to not check the user permissions. The passing of this parameter was added back to the addPlaylistToShow function and this removed the dependence upon initializing a user object with the hardcoded admin password. This fixes #103

Fixing dependence upon hard-coded password in AutoPlaylist

---

airtime_mvc/application/views/helpers/VersionNotify.php

This needed to take various git version into account as per https://github.com/LibreTime/libretime/pull/102#issuecomment-288707322.
It also had a bug where it would do the completely wrong thing with the currentParts array if a git commit-ish was treated as a version by mistake.

Make version comparision robust

---

python_apps/pypo/pypo/recorder.py

Some work for #42. There is probably more but this one leads ecasound being called again (and crashing).

Get base_recorder_file config from proper subsection in conf

---

airtime_mvc/application/views/scripts/showbuilder/index.phtml
airtime_mvc/public/css/dashboard.css
airtime_mvc/public/js/airtime/library/spl.js
airtime_mvc/public/js/airtime/showbuilder/main_builder.js
airtime_mvc/public/js/airtime/showbuilder/tabs.js

Makes the first tab remoeable and the tracks page be full width after removing the last tab. You can press the "Dashboard" link to open it back up again.

Hideable Scheduled Shows tab

---

airtime_mvc/application/controllers/UsersettingsController.php
airtime_mvc/public/js/airtime/library/library.js

When localStorage is empty we try getting the data from the server. This is a bit hacky since the ui uses a very old version of datatables.
Fixes #69

Restore datatables-library from server on login

---

airtime_mvc/application/configs/conf.php
airtime_mvc/application/controllers/ApiController.php
installer/vagrant/centos.sh
python_apps/api_clients/api_clients/api_client.py
python_apps/pypo/pypo/recorder.py

This is part 2 of fixing ecasound recordings from line-in. Part 1 restored the User-Interface, part 2 takes care of getting to the point where ecasound gets started, records something and uploads it through rest when done. Part 3 will take care of making sure that the recorded file is mapped to the show and not just stored as a new track.
I refactored api_clients to not use urllib2 for posting multipart data since I was loosing my sanity over it and requests seems to have a modern approach to doing this compared to what api_clients was previously doing.
This is a large part of #42 but there is still some more re-implementing to do. I'm PRing this now since I already spent way too much time to get it to this stage.

Fix recording through ecasound

---

installer/lib/requirements-debian-jessie.apt
installer/lib/requirements-debian-wheezy.apt
installer/lib/requirements-ubuntu-precise.apt
installer/lib/requirements-ubuntu-trusty.apt

I tested installing these in a docker container on each of the distros. The gir1.2-gstreamer-1.0 package is getting pulled in by the python-rgain package which I added to the list. I'm pretty sure this installs everything mentioned in #128.
Fixes #128

Install python-rgain and mp3 deps

---

airtime_mvc/application/auth/adapters/FreeIpa.php
airtime_mvc/application/common/GoogleAnalytics.php
airtime_mvc/application/configs/conf.php
airtime_mvc/application/models/Auth.php
airtime_mvc/application/models/FreeIpa.php
airtime_mvc/build/airtime.example.conf
airtime_mvc/tests/conf/airtime.conf
docs/freeipa.md
mkdocs.yml

Allow delegating user authentication to FreeIPA rather than having it be checked against the database.
With this feature I've ported everything I need to switch to LibreTime in my infrastructure. I did a ubuntu re-install to check if I don't break anything and have also been testing this on CentOS against a real FreeIPA server.
I've already started cleaning up the [v3.0.0.alpha.1 Milestone](https://github.com/LibreTime/libretime/milestone/2) and plan on doing another release soonish (ie. over the next couple of days unless lots of new bugs show up).

FreeIPA Auth Adaptor for LibreTime

---

python_apps/pypo/liquidsoap/ls_script.liq

There was an attempt to include library/pervasives.liq which was causing errors after #131 was merged. I think that this library is automatically included so I removed the include and it appears to be working. Hopefully this fixes #140

Remove hardcoded include of pervasives.liq

---

.gitattributes

Address issue #141 so Git cloning under Windows preserves line endings of relevant scripts and files regardless of a user's local Git configuration so it's possible to provision a VM with Vagrant, install and run LibreTime in place without issue.

Create .gitattributes to ensure proper cloning with Windows Git

---

installer/lib/requirements-debian-wheezy.apt
installer/lib/requirements-ubuntu-precise.apt
installer/lib/requirements-ubuntu-trusty.apt

As per the https://github.com/LibreTime/libretime/issues/145#issuecomment-292744215 it looks like we always need to install this.

Install curl on all platforms

---

airtime_mvc/application/controllers/LocaleController.php

Turns out the zf1 jsonHelper whas doing some weird stuff to the content-type header under the hood.
Fixes #145

Use json_encode if we need to return js and not json

---

utils/airtime-test-stream.py

As per the liquidsoap docs the file is loaded per default anyhow http://savonet.sourceforge.net/doc-svn/script_loading.html.
I think the output.shoutcast might be the only place where we really use it though. Testing this against shoutcast would be nice, but I don't have one and am not sure how relevant it still is.
Sorry again for breaking liquidsoap with #131 😞

Do not explicity load pervasives.liq

---

airtime_mvc/build/sql/defaultdata.sql
python_apps/pypo/liquidsoap/ls_script.liq

This shows up in places like *Off Air Metadata* as mentioned in #162 and others like the default stream setup.
Solution: Replace legacy upstream name with "LibreTime" in defaultdata.sql
I believe the file is not autogenerated so just changing it directly is the way to go.

Problem: legacy upstream name is still in defaultdata

---

python_apps/pypo/liquidsoap/__main__.py

It doesn't reconfigure python logging to get python debug output working as expected. This does not help for debugging #140 as there is already a debug log call that would output the actual URL being used.
Solution: Reconfigure python logging to output DEBUG log messages if `--debug` is passed.
Called as `airtime-liquidsoap --debug` the script will output the following should the connection to the api fail.
```
DEBUG:root:http://localhost:808/api/get-stream-setting/format/json/api_key/4ITVDK98D9USO9OLM7OA/
ERROR:root:HTTP request to http://localhost:808/api/get-stream-setting/format/json/api_key/4ITVDK98D9USO9OLM7OA/ failed
```

Problem: airtime-liquidsoap --debug only works for liquidsoap

---

Vagrantfile
docs/vagrant.md

Update Vagrantfile and docs for Debian as outlined in issue #170.

Switch Vagrantfile to use bento boxes for Debian #170

---

python_apps/pypo/liquidsoap/ls_script.liq

Lines 399 and 400. Changed the values of s3_name and s3_description places. 
(Because of this error, the Icecast confused the name and description of the flow)
_______________________
Строки 399 и 400. Поменял значения s3_name и s3_description местами. (Из-за этой ошибки Icecast путал название и описание потока)
_______________________
Sorry for my clumsy translation, I'm from Russia

Correction lines 399 and 400.  ls_script.liq

---

docs/faq.md
docs/manual/upgrading/index.md

This is to make it so it's clear that the update path is still more or less the same and adds all the new info I'm aware of that needs to be considered during the upgrade.
You can see the updated docs by [looking at the changed branch directly](https://github.com/radiorabe/libretime/blob/feature/update-docs/docs/manual/upgrading/index.md). I'm keeping the apt-get install stuff as is since we plan on re-adding it.
Please let me know if you have any more info or would want me to clarify something in the text and I'll be glad to add it here. I think this should cover both #184 and #178.
Fix #184 
Fix #178

Refactor upgrading docs

---

python_apps/airtime_analyzer/airtime_analyzer/metadata_analyzer.py
python_apps/airtime_analyzer/setup.py

This gets the mime type using file-magic in a most minimal way. Since the python bindings have been available as a distro package for quite a while it is written in a way so it should also run on pre pypi installs of file-magic. This means not being able to use nice things like magic.detect_from_filename due to the fact that they where added rather recently (with recently being 2 years ago).
As the mime type is only used to check for wav files that mutagen can't handle it only reads the mime type and ignores the charset and other attributes that magic can find.
Due to the fact that file-magic is not properly unicode safe I'm checking the file based on it's first 2048 bytes as per <http://stackoverflow.com/questions/34836792/python-magic-cant-identify-unicode-filename#comment57418632_348383 …

Use file-magic instead of python-magic

---

airtime_mvc/application/controllers/EmbedController.php
airtime_mvc/application/views/scripts/embed/weekly-program.phtml

This uses the available minimized version of angular instead of using the non minimized version from the google cdn. 
Fixes #167

Use the minimized angular from public dir instead of cdn

---

airtime_mvc/application/controllers/UserController.php
airtime_mvc/application/models/User.php

As described in #205 the default admin user can't be deleted. This stems from [the UserController trying to re-assign all the users files to the first admin it can find](https://github.com/LibreTime/libretime/blob/2b30a14744f857657f2e3b7e9c96713929343dd2/airtime_mvc/application/controllers/UserController.php#L207). In this case the initial admin is the user we are trying to delete. Since the controller can't re-assign the files to a new user deleting the user fails with a `foreign key violation: 7 ERROR:  update or delete on table "cc_subjs" violates foreign key constraint "cc_files_owner_fkey" on table "cc_files"` error.
Solution: Update the `getFirstAdmin` function in the user model to ignore the user being deleted. This way it finds a different admin to re-assign the files to and …

Problem: Deleting the initial admin won't work since it doesn't re-assign files

---

airtime_mvc/public/js/airtime/schedule/full-calendar-functions.js

The /Schedule/set-time-scale/format/json was being hit every time a new calendar page was displayed. The isn't good for performance reasons and also makes race conditions like #210 much more likely.
With this change the preference is only updated on the server when the GUI state changes because the user clicked on one of the "Day", "Week", or "Month" buttons.
This does not fix the locking issue completely, but it should help because the cc_prefs time-scale row in the database will get locked much less often. After applying this I wasn't able to reproduce #210 any more on an install with an extensive schedule.

Only update timescale pref in db on change

---

airtime_mvc/application/modules/rest/Bootstrap.php

`assert()` is a language construct in php 7 and not a function anymore. It also seems to behave slightly differently with regards to what kind of side effects assertions are allowed to have. This leads to all of the rest endpoints being broken in php 7 since the assertion silently fails and the routes never really get added to the front controllers router.
Don't wrap the `addRouter()` call in `assert()`. The way assert was being used was rather unusual for php code this age. It was also mostly checking zf1 rather than guarding against errors in LibreTime itself.
The php manual clearly states "As a rule of thumb your code should always be able to work correctly if assertion checking is not activated." giving even more reason to not wrap critical paths in assertions.
There are some other …

Remove assert() from rest module bootstrap

---

docs/faq.md

"What's with cue-In/Out points and silan?" is a frequently asked question that currently has multiple possible fixes and a couple of open tasks (not only "Why is it broken?" but also "Where is the cue-point editor?").
I added current infos to the release notes and was thinking this should be pointed out in the FAQ until we have a stable solution ready.

Add silan info to faq

---

composer.json
composer.lock

During composer install there are a couple of abandoned messages. This PR addresses the following one of them.
```
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
```
The change here is mostly in name and only contains some fixes concerning error handling and connection closing.
There is an upcoming 2.7 version of the lib that will need additional testing which is why I'd like to get this update into 3.0.0-alpha.2. It looks small enough and has worked on all distros I tried recently. The amqplib project still seems to support php 5.3 from the looks of it.

Bump phpamqp

---

build.sh

We don't need them for the end user runtime and this speeds up the
install quite a bit when installing from the full tarball.
Devs will need to run `composer install` to run unit tests locally
but that's about it.

Don't pull dev packages on install

---

airtime_mvc/application/views/helpers/VersionNotify.php
install

I fixed the manual installer to ensure that the VERSION file ends up
in the right directory on install.
I also took care of the pre-release parts of the naggingness. It shows
no updates as long there is no stable release for the current version.
As soon as one is available it uses the orange update icon to alert the
user that an update would be in order since a stable version has been
released.
Fixes #198, Thanks for the reminder in #246

Fix update warning

---

python_apps/pypo/pypo/pypofile.py

This adds TLS support to pypo when downloading files from the REST
API. I previously fixed some similar issues in the api_client and
wasn't aware that pypo isn't using it for every URL..
Fixes the problem from https://github.com/LibreTime/libretime/issues/175#issuecomment-316826523.

Use proper protocol in URL if port is set to 443

---

installer/lib/requirements-debian-jessie.apt
installer/lib/requirements-ubuntu-trusty.apt
installer/lib/requirements-ubuntu-xenial.apt
installer/vagrant/centos.sh

Currently pip is pulling a new pre-release version of pika. This
version does not seem to be backwards compatible and is the reason
why uploads fail on new installs.
Since there are packages available for pika on all major distros
we can get away with just installing those as pip will not try to
replace/upgrade them the way it is currently configured.
See #256 for more info on this issue.

Add python-pika to install script

---

install

The installer originally contained code to stop media-monitor on
updates. This code was removed together with media-monitor. In
the update case we want to make sure that media-monitor is never
running after updating to LibreTime.
The stop command will fail with a warning on systems that never
had media-monitor installed. This warning can be ignored and the
other services stopped with the same command still get stopped
as intended.
Fix #230

Disable media-monitor on update

---

airtime_mvc/application/controllers/LibraryController.php

This adds the functionality requested in #112 so that there is a duplicate smartblock option.
If you click the 3 dot context menu for a smartblock you will see the duplicate smartblock option added.
It works and copies over the criteria and type but it doesn't copy the block track contents for pregenerated static smartblocks. Since the primary purpose will be for dynamic smartblocks duplicating the existing contents didn't seem important and new content can be easily generated.

Duplicate Smartblock functionality added to menu context

---

airtime_mvc/application/controllers/PreferenceController.php
airtime_mvc/application/forms/GeneralPreferences.php
airtime_mvc/application/models/Preference.php
airtime_mvc/application/services/PodcastService.php
airtime_mvc/application/views/scripts/form/preferences_general.phtml
airtime_mvc/public/js/airtime/preferences/preferences.js

This adds an option to preferences that can be enabled when the Podcast Album Override is enabled that will automatically create a smartblock matching the newest item from a Podcast and a Playlist containing this Smartblock. This dramatically speeds up the creation of new automatic playlist shows from RSS feeds.

Enable Automatic Creation of Smartblocks and Playlists for new Podcasts

---

airtime_mvc/application/cloud_storage/Amazon_S3StorageBackend.php
airtime_mvc/application/cloud_storage/FileStorageBackend.php
airtime_mvc/application/cloud_storage/ProxyStorageBackend.php

These go way back to php 4 and don't need to be like this for any
reason. Currently error handling is acting up when these throw an
error.
This should take care of #289.

Update legacy constructors

---

.travis.yml
travis/python.sh

It looks like travis has activated python3 by default. This switches back to 2.7 for testing analyzer. This will also make #293 not fail anymore.

Fix python tests on travis

---

python_apps/airtime_analyzer/airtime_analyzer/metadata_analyzer.py

As shown by #279 the error message logged by analyzer when ingesting .wav files doesn't help debug cases where the `wave` module can't read the file. This adds the error message from the wave module to help in that case.

Better error message when parsing WAVE file

---

python_apps/airtime-celery/airtime-celery/tasks.py

This fixes #325 by addressing the root cause of the corrupt mp3 file.

Fix podcast corruption by adding decode = true to the raw request object for the celery task

---

python_apps/pypo/pypo/pypofile.py

Config file getting is allowed to fail. I didn't realize that it would not just use the default instead of excepting and getting caught. Sorry for that. 
I broke this with my changes in #329 this reverts them and blocks 2.0.0-alpha.3. Sorry again about that.
---
Add `protocol = http` or `protocol = https` to the general section of your airtime.conf.

Revert pypofile try block move

---

Vagrantfile

This fixes #353 and shouldn't cause any issues. Other than adding debian-stretch, it also changes the default suggestion to use debian-stretch vs. debian wheezy when someone types vagrant up debian.

Added debian-stretch to vagrant setup

---

airtime_mvc/build/airtime-setup/forms/rabbitmq-settings.php
airtime_mvc/public/setup/database-setup.php
airtime_mvc/public/setup/media-setup.php
airtime_mvc/public/setup/rabbitmq-setup.php
airtime_mvc/public/setup/setup-functions.php

This fixes #330 and #288 by having the rabbit-mq setup function write to the temp file when it checks the rabbitMQ settings.

Made rabbitmq settings write to tempfile upon check to fix install bug

---

airtime_mvc/application/common/FileIO.php

Comparing latest Libretime code to Airtime 2.5.1 song preview functionality, Airtime had no issues seeking to various points in time while previewing. Libretime however rarely worked when seeking to random spots in time.   After trying various things, and then reviewing the code for smartReadFile() function between Airtime and Libretime code, it became clear that at some point after 2.5.2 Airtime, a key call to fseek was removed which prevented seeking from working.
Adding this code back as is in Airtime 2.5.x line fixed the problem in my local setup of Libretime.

issue 349 - add missing code to allow preview seek

---

airtime_mvc/public/css/dashboard.css

While using Calendar mode to edit a show, advanced search was not available for the library objects. After reviewing the CSS through Chrome's Developer Tools, it was clear that the control was physically there, just could not be seen to click on.  Changing the z-index for the containing element allowed the control to be visible and enabled the functionality that had previously been blocked.

issue 350 - change z-index to allow advanced search in calendar mode

---

airtime_mvc/public/setup/media-setup.php

This is part of the requirement of hardcoded database values tracked on issue #356.
My change to fix #330 actually caused #360 because it wasn't properly writing the media directory and thus causing 
Error: Call to a member function getDirectory() on null in /vagrant/airtime_mvc/application/models/MusicDir.php:34 
Which results in a UI with no values whatsoever.
Changing this back fixes it, but it still probably is still dependent upon a hardcoded database password to work.
So we need to either rewrite the hardcoded calls to the php based propel inits or something else.

Fix - repoint to airtime-production-conf.php to resolve hardcoded values and broken install

---

airtime_mvc/public/js/airtime/playlist/smart_blockbuilder.js

The jquery activeTab.find included a variable that matched the css for the clear button. When I renamed the generate button this was also rewriting the HTML for the clear button thus overriding it's text.
By removing this from the identifier everything appears to be working with the text as it should be. I'm not sure why the jquery was written like that but based upon some testing the change doesn't alter the functionality.

modified jquery find for shuffle and generate buttons to not target clear button

---

airtime_mvc/application/controllers/PlaylistController.php
airtime_mvc/application/forms/SmartBlockCriteria.php
airtime_mvc/application/views/scripts/form/smart-block-criteria.phtml
airtime_mvc/application/views/scripts/playlist/update.phtml
airtime_mvc/public/css/styles.css

Basically I recreated what originally existed in the smart-block-criteria.phtml view and put it at the top of the track listing so that it will display with update.phtml and be updated when the criteria is changed and saved.
I'm not 100% happy with how this changes the UI but it is definitely the easiest option at this point and avoids touching the javascript to try to update it. Any suggestions for UI improvements are encouraged.  It might make sense to color it with CSS to make it more distinct but otherwise I think that this reimplements the functionality requested in #366

Moved display of smartblock files that meet criteria to update.phtml

---

airtime_mvc/application/views/helpers/VersionNotify.php
build.sh

Fixes #410 by using Composer\Semver\VersionParser to validate the contents of what we got from VERSION before comparing anything.
If anyone installs from a source lacking the version file it should look like this:

Validate contents of VERSION file

---

.github/invite-contributors.yml

Configuring invite-contributors as per #434.
I'll activate the app as soon as the config is merged.

Configure invite-contributors probot app

---

airtime_mvc/application/controllers/PluploadController.php
airtime_mvc/application/views/scripts/plupload/index.phtml
airtime_mvc/public/js/airtime/library/plupload.js

This grabs the upload limit for the js frontend from what is configured in php on the backend. I figured grabbing the appropriate value from the php config is simpler to handle than exposing the option in settings.
I ended up keeping the limit at 500 MiB for users that configure their server to support unlimited uploads. We could get a further estimate of the possible upload size by checking their memory_limit value but I feel like that would be going to far.
Fix #384

Use max upload size from php config in frontend plupload js

---

python_apps/pypo/liquidsoap/ls_lib.liq

When Libretime streams a webstream, the ID3 data is put into a single title field, leaving the artist field blank. When processing the ID3 data, Libretime concatenates the blank 'artist' field with the title, leaving '- title'. ShoutCAST rejects title updates that begin with punctuation for stylistic reasons (thanks guys) and so effectively ignores all ID3 data coming with the stream, falling back to the 'Station off-air' message. This PR uses the title field alone if the artist field is blank, but both when the artist data is available e.g. when streaming an MP3.

Stop ShoutCAST rejecting title updates

---

airtime_mvc/build/airtime.example.conf
install

Media monitor was removed and we can remove it from the install.
It is to be confirmed if this fixes #450 but we should still get rid for the `[media-monitor]` section during the install so we don't trigger the bits of code I linked in https://github.com/LibreTime/libretime/issues/450#issuecomment-369905183.

Remove obsolete settings from master config template

---

install

a simple addition to get the installer to recognise Raspbian 9 (stretch) as debian stretch,  which is needed for a successful install on raspberry pi under the latest OS

Fix to the installer to enable successful install on Raspbian 9 (stretch)

---

airtime_mvc/application/controllers/FeedsController.php

I'm building an archive page for our station that will pull libretime's podcast feed. I needed to add CORS support to the file, and noticed libretime already handles CORS responses for other resources.

Add CORS handling to podcast feed

---

python_apps/airtime_analyzer/airtime_analyzer/message_listener.py

The plain `type` argument was deprecated somewhere around pika 0.11.0/0.12.0 (aka ages ago) and it is slowly getting removed now. I found this https://github.com/pika/pika/commit/9598b4391647ca0a9e0e48dbe87d66aa116dae50 and https://github.com/pika/pika/commit/3a99d8d0f7bb46c9ecedebdc698246e5cb912994 that work on the param I'm updating and the change needed is documented ie. https://github.com/pika/pika/issues/353#issuecomment-18845184 and elsewhere.
This was also reported in a thread in our issue tracker https://github.com/LibreTime/libretime/issues/474#issuecomment-381393754.

Fix call with deprecated arg

---

airtime_mvc/application/services/PodcastService.php

This fixes #228 and is super simple, if we ever do a SaaS billable version it might make sense to add a UI to make this number variable. But at this point lets just push it under the rug and let our users subscribe to as many podcasts as they want too.

Made podcast subscription limit depend upon SaaS billing flag

---

docs/vagrant.md

Removes `ubuntu` and `debian` options, updates `debian-wheezy` to mark it as deprecated and, adds some more info on `centos`.

Update matrix of supported distros

---

airtime_mvc/application/controllers/ApiController.php
airtime_mvc/application/models/RabbitMq.php

Searching for [SendMessageToHaproxyConfigDaemon](https://github.com/LibreTime/libretime/search?utf8=%E2%9C%93&q=SendMessageToHaproxyConfigDaemon&type=) reveals that the code is indeed dead. The `//send ip, subdomain` has no other side-effects.

Remove dead Haproxy messaging code

---

airtime_mvc/build/sql/defaultdata.sql

This will fix #578 by adding the entries to cc_pref to enable the podcast album override and smartblock add by default.

Modified the database to turn on the podcast album override by default

---

utils/make_tarball.sh

More #561 cleanup. The actual release tarballs are built with `dev_tools/release/release.sh` and this isn't in the path of anything related to it.

:recycle: (utils) Remove unused make_tarball.sh

---

airtime_mvc/application/views/helpers/VersionNotify.php

Wrapping version in Array() to comply with SemVer new method signature. This should fix issue #487. Tested on Ubuntu 18.04. with PHP 5.6 with 3.0.0-alpha5 (7.2 or 7.0 is still incompatible, see issue #580)

Fixing failing version test

---

airtime_mvc/application/views/scripts/schedule/add-show-form.phtml
airtime_mvc/public/js/airtime/schedule/add-show.js

this commit collapses by default several sections of the add/edit show dialog:
why?
- simplify interface. less distraction for users and less need to scroll way down to the "update show" submit button
- prerequisite to proposal i'll work on now to improve the autoplaylist UI
problems? 
- only that i would have like to have those little orange triangles rotate indicating open/closed state, but that'd require too much (crappy) code and time.

UX: collapse advanced configuration sections in Schedule Dialog

---

airtime_mvc/application/models/Preference.php

This is another attempt to fix #487 (the original issue, not the regression stemming from #594) based on my hunch that it's an issue with reaching the GitHub API. This underlying issue might also be triggerable by temporary outages or potentially rate limiting on the API side but I could only simulate the obvious cases I could see in my testing.
In any case this depends on #600 getting merged so we are back to a deployable master branch.

Version check when GitHub is not available

---

airtime_mvc/application/models/Block.php

Basically there was what I think is an unnecessary escaping of the values with the php function htmlspecialchars
I don't think this is necessary as it isn't done for any of the other strings that take characters and there is escaping done later on when the query is built.
This fixes #328 and so you can find your drum and bass with D&B in both the Genre & Smartblock

removed php escape of characters that broke smartblocks

---

airtime_mvc/application/forms/SmartBlockCriteria.php
airtime_mvc/application/views/scripts/playlist/update.phtml

This fixes #541 evidently in one of the last commits of #370 I inadvertently deleted the code from the update.phtml template that actually displayed the results of poolCount. This restores that and fixes the problem.

Smartblock criteria show # of matches fixes #541

---

airtime_mvc/application/controllers/downgrade_sql/airtime_3.0.0-alpha.7/downgrade.sql
airtime_mvc/application/controllers/upgrade_sql/airtime_3.0.0-alpha.7/upgrade.sql
airtime_mvc/application/forms/SmartBlockCriteria.php
airtime_mvc/application/models/Block.php
airtime_mvc/application/models/airtime/om/BaseCcBlock.php
airtime_mvc/application/upgrade/Upgrades.php
airtime_mvc/build/sql/schema.sql
airtime_mvc/public/js/airtime/library/library.js
airtime_mvc/public/js/airtime/playlist/smart_blockbuilder.js

This will make the dynamic smartblock the default choice vs. the static smartblock. Unfortunately this change requires updating the database and various changes to the default behavior. It needs testing and review to make sure the database changes take place on pre-existing instances.

Change dynamic smartblock to be default

---

airtime_mvc/application/views/scripts/playlist/update.phtml

This fixes an unintentional side effect of #627 where criteria was showing on non-smartblocks such as playlists.

Fix: don't show criteria matches on playlists

---

python_apps/airtime_analyzer/setup.py
python_apps/airtime_analyzer/tests/metadata_analyzer_tests.py

This fixes #610 and possibly other issues regarding mutagen. In theory it could introduce new bugs but I suspect the version restriction wasn't necessary and was geared towards simply avoiding the need to rewrite tests.  We can respond to new issues if we are able to find them but this should fix a number of potential issues based upon the number of [bug fixes](https://mutagen.readthedocs.io/en/latest/changelog.html) from 1.31 to 1.41.

Remove the version restriction on mutagen

---

install

This fixes #427 by making Y be the default if a user hits enter without typing in a value.
I think this is the best option because typically a capital letter indicates the default behaviour and so users may expect that and hit enter and thus causing errors down the line. This could prevent some issues that people have reported where we have needed to tell them ./install -fiap 
Also if people hit n or N or any other value it won't install the service.

made Y default value for install script

---

python_apps/airtime-celery/airtime-celery/tasks.py
python_apps/airtime_analyzer/setup.py
python_apps/airtime_analyzer/tests/metadata_analyzer_tests.py

This fixes #519 by taking away the mp3 specific code and replacing it with mutagen library as a whole which supports most filetypes except for WAV, and I don't think there are very many WAV based podcasts.
I tested it with the m4a based podcast referenced in #519 and was able to download without an issue whereas before it was failing.
Also fixes #271

Fix nonmp3 podcast download

---

airtime_mvc/application/controllers/PlaylistController.php

This fixes #646 
Basically keeps the code from calling block specific functions when a playlist isn't a block.

prevented shuffling from failing on playlists containing smartblocks

---

python_apps/airtime_analyzer/airtime_analyzer/analyzer.py

I was looking at the base class in analyzer wanting to clean it up some and ended up removing some dead code and fixing some formatting and a docs typo.
I wasn't able to refactor it into a proper abstract base class as described in [this tutorial](https://www.python-course.eu/python3_abstract_classes.php) due to us not supporting python3 yet.
I opted not to implement a [hack](https://stackoverflow.com/a/4474495) but rather to leave this be and drop a TODO that tells us [what to do](https://stackoverflow.com/a/31590500) once we can drop python2 support.

Cleanup airtime_analyzer/analyzer.py

---

airtime_mvc/application/Bootstrap.php
composer.json
composer.lock

Remove zfdebug since it is unused and has a dependency on zendframework1. I found this when looking into #580. 
If we get rid of it now it there should be no side effects and we won't have to take care of it if/when we switch to a different zf1 implementation (or a different framework for that matter).

Remove zfdebug

---

dev_tools/release/release.sh

This is needed because quilt cannot patch line-endings correctly and the Zend framework uses some CRLF line endings instead of LF. The differences result in the package build failing.

Convert all line endings in the tarball to unix

---

airtime_mvc/public/css/styles.css
airtime_mvc/public/js/airtime/library/library.js
airtime_mvc/public/js/airtime/showbuilder/main_builder.js

Fixes #339
this pr is my suggestion of a better way to approach adding focus to the library search input. i'm proposing it _instead of_ #658 . 
- also removes a [wierd hack](https://github.com/LibreTime/libretime/blob/14ba51489054b91f3cfd58d1390b2dedfb32ab03/airtime_mvc/public/js/airtime/showbuilder/main_builder.js#L134) i found while reviewing #658.
- no longer dependent on resolution of #660

Add focus to library filter input upon load

---

airtime_mvc/public/css/fullcalendar.css

fixes #665
oops my bad, forgot to check the week view

fix Calendar - Long titles now overlap 'files bar'

---

install

Jessie is out of security support and will be dropped inLibreTime 3.0.0-alpha.8
Fixes #684

Installer - Add warning for the deprecation of Debian Jessie

---

airtime_mvc/application/configs/navigation.php

As reported in #698 we made the user edit menu unreachable in #489.
This make the main "Settings" menu item to be visible to all users and also points it straight to the profile edit page where they can change their data and password.
For admins the general settings page is still reachable through the submenu below "Settings".
Fixes #698

Make Settings menu visible to all users

---

docs/vagrant.md

There were a couple of errors, resulting in failures to build vagrant boxes

Fix vagrant libvirt instructions

---

airtime_mvc/application/services/PodcastEpisodeService.php

So this was inspired by #464 
and fixes #675
The problem is that SimplePie appears to not support multiple enclosures of different types. At least with my test URL. From the [SimplePie docs](http://simplepie.org/api/class-SimplePie_Item.html#_get_enclosures)
```get_enclosures( )
Get all available enclosures (podcasts, etc.)
Supports the <enclosure> RSS tag, as well as Media RSS and iTunes RSS.
At this point, we're pretty much assuming that all enclosures for an item are the same content. Anything else is too complicated to properly support.```
So we had to manually search through the tags find enclosures and then look for audio ones and create a new enclosure object based upon these attributes.
This worked for my test URL but it would be handy to test it on others as well.
It only does …

fix podcast non audio enclosure problem

---

airtime_mvc/application/layouts/scripts/layout.phtml
airtime_mvc/application/views/scripts/partialviews/header.phtml
airtime_mvc/public/css/masterpanel.css
airtime_mvc/public/css/styles.css
airtime_mvc/public/js/airtime/dashboard/dashboard.js

this is an opinionated second half of a solution to https://github.com/LibreTime/libretime/issues/698
it does this:
i also removed the timezone since IMO it isn't something that changes needs prominence.
i'd also like to actually hide the update indicator for non-admin users, but haven't since i wanted to hear whether folks think that's a good idea. i've had to explain to radio collective members about updates etc., and it's been more of a distraction than anything else. if this does sound like a good idea i could use some guidance regarding possibly modifying `VersionNotify.php`

masterpanel ui tweaks

---

airtime_mvc/application/common/FileDataHelper.php

This solves an issue posted in #509 that was unrelated to the preview but was indeed causing some flac files to fail to play.
Basically for some reason the getAudioMimeTypeArray had audio/flac-x  but not audio/flac and so files that showed up as audio/flac would give a 400 error when the airtime-playout tried to download them.
This fixes it but still doesn't fix the preview.

add audio/flac to mimetype in filedatahelper

---

airtime_mvc/application/models/Schedule.php

This just gets rid of a php 7.2 null count warning error that is breaking an API call.

Fix count warning in schedule

---

airtime_mvc/application/models/Scheduler.php

This fixes #759 by preventing an unnecessary attempt to convert a timestamp formatted variable to a time stamp variable which causes errors due to attempting arithmetic improperly. If the comments are to believed this should fix the problem and it does remove the error and allow people to move items in the schedule.

added check to prevent unnecessary conversion to seconds

---

airtime_mvc/public/js/airtime/library/podcast.js

restores this button: 
visible at `/podcast/station`
broken by my earlier podcast ui work.

restore my podcast episode delete button

---

airtime_mvc/application/controllers/ApiController.php

As per feature request: [#799](https://github.com/LibreTime/libretime/issues/799)
I'd like to see the show source status exposed via the live-info-v2 API to allow 3rd party scripts to make show-type-based decisions.  e.g., posting to social media, or triggering recording, etc.

Expose source status via live-info-v2 endpoint.

---

airtime_mvc/application/models/Scheduler.php

This fixes #273 by overriding a section of the validateRequest that would always fail if you were cancelling a linked currently playing show. It appears to be working for me.

enables cancel show for currently playing linked shows to work

---

.travis.yml
dev_tools/release/release.sh

Hopefully this fixes the continued nightmare that is trying to release a deb using a git managed tarball with mixed line-endings. It also adds a dependency to travis on dos2unix, which is required in the release script

Exclude gitattributes from release tarball

---

docs/manual/getting-started/index.md

This fixes the fact that recaptcha was removed in #649 and adds a link to #724 stating that we haven't yet provided documentation for how to setup PHP mail but that it is possible for password resets.

removed recaptcha and added password reset issue link

---

airtime_mvc/application/modules/rest/controllers/PodcastController.php
airtime_mvc/public/js/airtime/library/library.js

This adds a new field to the podcast datatable called Import Date which is basically the last time an episode was automatically downloaded by the system. This can be helpful in tracking podcasts that aren't being updated. 
This only updates when the system ingests the podcast and it also doesn't catch failed attempts where there is an issue with the RSS feed. They'll still have the date updated if there are new items even if it fails to download them.
I made it visible by default.

Add podcast import date column to podcast page

---

airtime_mvc/application/forms/SmartBlockCriteria.php
airtime_mvc/application/models/Block.php

This fixes #775 by adding the ability for smartblocks to be sorted by the most recently played tracks (tracks that were played recently come to the top) or least recently played (tracks that were never played come to the top of the list and it is basically randomly selecting between tracks that match the criteria that have never been played and then if all tracks have been played once based upon the 'lptime' track it'll play the track that was played furthest in the past.
This will allow smartblocks to choose unplayed tracks by setting the sort order to be least recently played.
The docs should also be fixed include this new option but we still need to rewrite the existing smartblock docs page.

Smartblock sort tracks by last play date

---

airtime_mvc/public/js/airtime/library/library.js

This fixes #819 and focus still goes back to the library search otherwise.

do not take focus away from advanced search fields

---

Vagrantfile

The official Debian Buster Vagrant image is out. We should move to it instead of using an unknown provider

Use official Debian Buster Vagrant image

---

python_apps/pypo/pypo/pypofile.py

This disables the file size check in pypos cache because I assume some `os.path.getsize` issues lead to #758 
I'm only removing the fs check as per https://github.com/LibreTime/libretime/issues/756#issuecomment-477853018 f. (ie. without any replacement using md5 sums or whatnot). My reasoning for doing so is best explained here: https://github.com/LibreTime/libretime/issues/756#issuecomment-515759233 & https://github.com/LibreTime/libretime/issues/756#issuecomment-516098013.
Additionally, this commit adds a large comment to help us not forget about the assumption that is now in pypo's caching layer . We need to remember to look at this with #70 et al. In the long term we need to implement a more serious caching strategy in pypo.
This tentatively fixes #756.

Remove fs block size based check in pypo cache

---

installer/vagrant/centos.sh

The packages that used to come from the PUIAS repository have mostly been upstreamed to Fedora EPEL with some audio codecs now residing in Nux Dextop.

Remove puias dependency (now covered by epel, nux)

---

python_apps/pypo/pypo/__main__.py

This gets rid of [a patch](https://build.opensuse.org/package/view_file/home:radiorabe:airtime/libretime/python-275-compat.patch?expand=1) that I have been applying to my CentOS 7 packages after having been a bit overzealous when I refactored pypo in #654.

CentOS 7/Python 2.7.5 compat fix

---

airtime_mvc/public/index.php

This check used to ensure that SaaS users never got to see the setup page.
Should anyone want to ensure that the setup page is never displayed, the straightforward way is to ensure that the config file always exists (the setup routine only gets triggered if airtime.conf is missing).

Remove airtime.pro servername check in setup

---

airtime_mvc/public/css/styles.css

Fixes that the scrollbar was getting displayed in tooltips on the schedule page.
**Current behaviour**
**With change**

Fix text overflow in tooltip

---

airtime_mvc/public/css/styles.css
airtime_mvc/public/js/airtime/schedule/full-calendar-functions.js
airtime_mvc/public/js/airtime/schedule/schedule.js

This displays a warning icon with corresponding tooltip on the schedule page if a show is overbooked. The following screenshots show how it looks while hovering over the icon.
**month overview**
**week view**
It does not display this warning on autoplaylist based shows since it is expected that they usually are slightly overbooked. The icon i'm using isn't used anywhere else as far as I can tell. I'm also removing a dead js function that used to do something similar.

Schedule: Display warning icon and tooltip on overbooked show

---

README.md

Realised we probably should link to mattermost in the README too

Add link to mattermost in README

---

Vagrantfile

NFS sync fix for Mac users updating to the new OS. Due to the changes in Catalina with their dedicated system volume we have to change the Vagrantfile in order to point to the install file, else it won't work.

macOS Catalina support for Vagrant

---

airtime_mvc/application/controllers/ApiController.php

Removed 1024px for artwork in API. This was old code from before the merge and forgot to remove them on the API. Most artwork available for these audio files (from Apple Music, Amazon, ect...) are around 500px - 600px, so it doesn't make sense to enlarge a thumbnail at that size... it also made uploading take a little longer.
The default value is now 512px if using just "artwork" in api to get track info by ID. (eg. http://192.168.10.100:8080/api/track?id=1&return=artwork)
The default url for artwork, like the example above is also available in the API for live-info. Whenever you guys have a chance you can merge so nobody runs into any issues if using the API.
I will try to work on the artwork upload from the edit tab soon.

Artwork fix in track API

---

.github/lock.yml

I activated the [lock probot](https://probot.github.io/apps/lock/) after our discussion in #434.
Before the the bot every had any work to do it was refactored to mandate needing a config file in `.github/lock.yml`.
This PR finally adds such a configuration and configures it to post a comment that points people finding such issues our discourse and chat.

Config for lock bot

---

.github/stale.yml

This issue prepares the configuration for the [stale probot](https://github.com/probot/stale). If we decide to merge it I will activate the bot after the merge.
The issues closed by the but will get tagged as *wontfix* and a comment will be added. These comments will look similar to the image below.
For our case I replaced the stock test with the following.
> This issue has been automatically marked as stale because it has not had activity in the last 5 months. It will be closed if no activity occurs in the next month.
>  
> Please chat us up on [discourse](https://discourse.libretime.org/) or ask for help on our [chat](https://chat.libretime.org/) if you have any questions or need further support with getting this issue resolved.
>
>  You may also label an issue as *pinned* if you would …

Configure stale bot

---

Vagrantfile
docs/vagrant.md

Replaces `bento/debian-9.6` with `bento/debian-9` which always points to the latest point release and moves Debian Buster over to the bento image to stay consistent with the other images.

Update Debian Vagrant Boxes

---

python_apps/pypo/pypo/pypomessagehandler.py
python_apps/pypo/pypo/pypopush.py

This fixes #906 
Finally I found out the main issue causing desynchronization between the MVC and Liquidosap was that the RabbitMQ got stale after a while (less than an hour), then schedules were only updated on PypoFetch time out.
The gotcha here is we were using a SimpleQueue, which's 'python-like' *get*  method apparently doesn't handle recovery well. Kombu Consumers are the way to go instead.

PypoMessageHandler reliable RabbitMQ consumption

---

airtime_mvc/application/controllers/ScheduleController.php

I've found this is because of ScheduleController L305, introduced recently
https://github.com/LibreTime/libretime/commit/45dbf8475060e14a56dae4d9389ff8546a69bc09
A simple if clause allows us to workaround the issue, which must be that live streams don't have pictures nor metadata...
Fixes #919

input streams on ports 8001 or 8002 break the MVC

---

airtime_mvc/public/js/airtime/dashboard/dashboard.js

The issue in the dashboard was when scheduling elements which do not have metadata (for instance, a webstream, or a live input stream). 
This basic not null check was missing in javascript .
fixes #924
may be related to #919 and #921

Fix Dashboard when current instance has no metadata

---

python_apps/pypo/liquidsoap/__main__.py
python_apps/pypo/liquidsoap/liquidsoap_auth.py
python_apps/pypo/liquidsoap/ls_lib_legacy.liq
python_apps/pypo/liquidsoap/ls_script_legacy.liq

This fixes #192 and pulls the fixes @hairmare added for liquidsoap 1.3 compatibility while creating a legacy version of the scripts that will be used if the user has liquidsoap 1.1.1 (ie if they are running any Ubuntu version before 19.10 since 14.04 and probably Debian stretch). So this should allow us to start supporting Liquidsoap 1.3 immediately without breaking thing for people using Ubuntu. If we decide to quit supporting 16.04 & 18.04 in the future we can easily remove this.
I kept the changes in liquidsoap_auth.py but I haven't been able to confirm that this doesn't cause an issue with connecting on a older system as I couldn't get my local test system to connect via the show or master mount and I'm not sure if this is an issue caused by this script or is unrelated at this point …

add liquidsoap 1.3 support while retaining legacy script for liquidsoap 1.1.1 compatibility

---

mkdocs.yml

The install processes is the first thing users need to do, thus list it
first

List install first in docs

---

airtime_mvc/public/setup/database-setup.php
install
installer/lib/requirements-debian-buster.apt
installer/lib/requirements-debian-jessie.apt
installer/lib/requirements-debian-stretch.apt
installer/lib/requirements-ubuntu-bionic.apt
installer/lib/requirements-ubuntu-precise.apt
installer/lib/requirements-ubuntu-xenial.apt
installer/lib/requirements-ubuntu-xenial_docker_minimal.apt
installer/vagrant/centos.sh

This is my almost working attempt to update the default icecast password.
It fixes #86 by automagically generating a password for icecast.
I am running into an issue where the prepared PDO SQL statement to insert the password into the database doesn't appear to actually run and so there is a bug somewhere in there. 
Once I can figure that out it just needs more testing but should be ready to rock. I'm pushing it right now in case anyone wants to review it and point out what I'm doing wrong, otherwise I'll come back to it later and figure it out.

change default icecast password automatically during install

---

install

This prevents the issue where the icecast  password is changed when the database already exists.

made sure that icecast pass is not changed upon upgrade or reprovision

---

python_apps/airtime_analyzer/setup.py

This PR closes #959.
I'm not sure how to do a full blown test to ensure this works but considering the change from >=1.41. to ~=1.43.0 there's a high confidence this is safe to merge.

Set mutagen~=1.43.0 until LibreTime moves to python3

---

airtime_mvc/application/layouts/scripts/layout.phtml

Disabled version notification to avoid confusion (plus it was getting a bit annoying), and left note. 
I wasn't getting any result for latest. Will look into it later on. For now, maybe it's best if we keep it disabled for new users. We might have to change it so this notification is visible to admins only, or perhaps remove completely since we can already see latest in Settings > Status. But that can be discussed later.

Disable version notification

---

python_apps/pypo/pypo/telnetliquidsoap.py

The `kick` command has been removed since Liquidsoap [1.3.2](https://github.com/savonet/liquidsoap/blob/master/CHANGES.md#132-02-09-2017) as it was a duplicate of `stop`. Thus, source disconnection is broken and especially the DJ one - which is quite problematic for scheduled shows.

Fix source disconnection with recent Liquidsoap

---

python_apps/pypo/liquidsoap/airtime-liquidsoap.logrotate

Running at least Debian Buster, the current logrotate configuration for airtime-liquidsoap put the logrotate service in failure since the postrotate command fails. As the airtime-liquidsoap script is managed by systemd, this command is replaced to use systemd to send the `SIGUSR1` signal and prevent any failure with ` || true`.

Fix postrotate command of airtime-liquidsoap

---

airtime_mvc/build/airtime-setup/load.php

This fixes #662 - as far as I can tell the issue in the code wasn't related to Systemd but some change I don't fully understand because I'm not sure why it was coded like this in the first place.
Basically I removed the && status == 0 and simplified the check to simply check if $out which is the command result from pgrep was greater than 0. This made it work under Debian Buster. It should work on the other systems as well but needs testing.
I wasn't sure the purpose of $status == 0 was and for some reason the array_exists check that was there previously was providing a false positive when I removed the status check.
I think that this is a simpler way of doing things and it seems to work. 
I also removed the -u www-data from the pgrep because that seemed like an unnecessary check that …

Simplified status page check to work under Debian

---

mkdocs.yml

This might work for #986 
Since pages was deprecated and navs is now preferred, I am wondering if switching to navs will somehow fix the broken links for tutorials.
It is a difficult thing to troubleshoot because it works on local mkdocs instances but so far the github deployed version is suddenly broken. Anyways, this shouldn't hurt and might the lack of inclusion.

changed pages to nav due to deprecation of pages in mkdocs

---

airtime_mvc/application/configs/navigation.php
airtime_mvc/application/controllers/EmbeddablewidgetsController.php

This fixes #452 in the simplest way possible, by removing the widget from the navigation. The widget would require various updates to conform with the current Facebook API and we don't have anyone who has volunteered to work on it. The other option would be to delete the code but this seems like a good first step.

Remove facebook widget link

---

airtime_mvc/application/layouts/scripts/layout.phtml

This fixes #783 - which only shows up currently when a new user logs in to a system that was updated from Airtime 2.5.x - we might want to put more information in here at some point but this just removes the reference to Airtime.pro

Change Airtime modal to simple LibreTime intro

---

.travis.yml

This is an attempt to fix #986 - as the build logs are showing warnings related to the beta travis CI 2.0 or dpl v2 command line
For instance 
```
Build config validation
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
root: key matrix is an alias for jobs, using jobs
deploy: key api_key is an alias for token, using token
deploy: key github_token is an alias for token, using token
env: key …
```

Make travis CI use 1.0 explicitly

---

airtime_mvc/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql

This should fix the issue with auto upgrades. I tested it on Ubuntu Xenial vagrant box and the use of serial worked whereas the previous code was failing to create the DB.

changed track type id to serial for auto increment

---

travis/python.sh

I'm not sure if this will disable updates of mkdocs but evidently our current mkdocs settings are not building any ways so it should fix the tests in the meantime.

Removed mkdocs build from TravisCI tests

---

airtime_mvc/public/js/setup/setup-config.js

This should fix #984 by moving the scrollbar to the top on any new page load. Thus preventing the top of the message from being cut-off as indicated in the bug report.

if the screen is small enough to have a scrollbar always go to the top

---

airtime_mvc/build/airtime-setup/forms/rabbitmq-settings.php

This kind of fixes #1026 - I tried wrapping the rabbitmq password in the conf file as a solution which allowed it to work but then the python services such as airtime_analyzer failed to read it correctly. I also considered doing jquery validation etc but didn't make much progress.
So I figured just adding a text warning in the description on the rabbitmq setup screen is a good stop-gap that should hopefully mitigate this issue some.

Add a warning to avoid special characters in rabbitmq password

---

python_apps/pypo/pypo/listenerstat.py

Correctly encode icecast admin credentials for listener stats

---

airtime_mvc/application/common/FileDataHelper.php

Don't throw an exception on corrupted cover art image data in upload. The order of processing needs to be the other way around.

Corrupt Cover Art prohibits mp3 upload

---

airtime_mvc/application/common/HTTPHelper.php
airtime_mvc/application/configs/conf.php
airtime_mvc/application/controllers/EmbedController.php
airtime_mvc/application/views/scripts/embed/player.phtml
airtime_mvc/build/airtime.example.conf
airtime_mvc/public/js/airtime/player/playerhtml5.js
docs/install.md

Like in many other software projects, there are issues when you reverse-proxy from SSL to a non-ssl backend. The elegant but error-prone way would be auto-detecting proxy headers in the HTTP request. (What if a misconfigured or prior-unknown reverse proxy is used?) I have used another proven approach and added a force_ssl parameter to the general section of airtime.conf, The patch is non-invasive as with a working configuration it is ignored. Python is not my home turf but i'll try to wrap my head around it.

Add a switch to force 'assume SSL' mode behind a reverse proxy

---

docs/gemfile

Bump kramdown dependency to 2.3.0 to address https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
~Do not prompt for confirmation in install of packages required for docs as this breaks Vagrant~

Docs Kramdown dependency bump to 2.3.0

---

python_apps/airtime_analyzer/airtime_analyzer/replaygain_analyzer.py

'text' argument was added in Python 3.7 as an alias of 'universal_newlines'. Using 'universal_newlines' works on Python 3.5/3.6 and should be forward-compatible.

Fix replaygain_analyzer in Python 3.5

---

install

Fixes removing the config file on re-running install. This somewhat addresses LT handling upgrades badly when using `./install`. The issue was that it was grepping for `[media-monitor]`, which was being interpreted as a regular expression, and so matching lines with any of those digits in them. Thus, it always thought it needed to migrate from media-monitor and scrap the old config file

Force fixed strings on grep for media-monitor

---

docs/_docs/live-broadcast.md

It wasn't being shown in the links on the website

Docs: Add live-broadcast to interface category

---

install

The way those variables are formatted, the `[` and `]` surrounding the condition make them evaluate incorrectly

Fix Ubuntu condition checking for add-apt-repository

---

Vagrantfile
airtime_mvc/application/upgrade/Upgrades.php
airtime_mvc/public/setup/database-setup.php
airtime_mvc/tests/application/helpers/AirtimeInstall.php
docs/_docs/vagrant.md
install
installer/vagrant/centos.sh

Update CentOS Vagrant environment to CentOS 8. The changes to the database routines work on `.deb` based platforms as well, everything else is specific only to the `centos.sh` Vagrant init script.
Fix #1113

fix: update to CentOS 8

---

airtime_mvc/application/views/scripts/embed/player.phtml

ForceHTTPS = false ; It was causing issues on fresh install where the player would not play from the mountpoint because of https conditon.

Removed HTTPS condition from source of player

---

installer/vagrant/centos.sh

This was missing from #1139. We need to use 3.8 since it's easier to use pycairo than with 3.6 and we also install psycopg in preparation for using the CentOS vm with the Django api from #958.

fix(centos): update to python 3.8 and install psycopg

---

python_apps/pypo/pypo/pypofile.py

This was introduced by #1165, `fallback` is a keyword only argument - see [the doc](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.get). I didn't provided any test as it seems not covered for the moment, and regarding the - amazing and uplifting - coming changes, it is maybe not needed as of now…

Fix missing 'fallback' kwarg for base_port in pypofile

---

airtime_mvc/application/common/AutoPlaylistManager.php

When building list of instances with autoplaylists, filter out those where modified_instance is true.
This should resolve issue #1126.

Add check for deleted instance to AutoPlaylist

---

.github/workflows/package-release.yml

Fixes the tag regexp and removes running on pushes to master

Do not run release on every push to master

---

python_apps/api_clients/api_clients/utils.py
python_apps/api_clients/tests/utils_test.py

Allow schedule times without microseconds in api_client

---

python_apps/api_clients/setup.py

isoparse was implemented in version 2.7

Require python-dateutil version 2.7 or higher

---

python_apps/airtime_analyzer/setup.py

Set max version for PyGObject so that it does fail install looking for `py3cairo`.
Install tested in vagrant
Vagrant up debian-buster

Limit pygobject version to 3.36.1 for pycairo

---

python_apps/api_clients/api_clients/version2.py
python_apps/api_clients/setup.py
python_apps/api_clients/tests/version2_test.py

Fixes: #1258
Currently I'm unable to test, so requires feedback from @matias-tecnosoul

Set default replay gain

---

airtime_mvc/application/controllers/ApiController.php
python_apps/api_clients/api_clients/utils.py

Add request method and payload to api_client http error handling, as we have some obscure behavior in this area.
Let the requests library encode the JSON payload if present.
Handle bad payload in some airtime_mvc api calls: Added a basic JSON decode error safe guard for the following actions:
- pushStreamStatsAction
- updateStreamSettingTableAction

Better error handling in api_client and airtime_mvc

---

install

When installing Icecast manually, we don't want the installer to interfere with the icecast.xml config file by changing the passwords.
The script fails trying to copy the Icecast password file it didn't create.

Fix installation failure on install -fap

---

.github/workflows/test.yml

In order to simplify any CI platforms and versions addition, we should use a test matrix and add our details in it, instead of copy pasting the entire test job.
Related-To: #1168

ci: use test matrix for php and python tests

---

python_apps/pypo/pypo/timeout.py

Python 3.9 compatibility fix.
From the following stack trace on Debian bullseye and python 3.9:
```
Aug 15 18:41:07 debian11 airtime-playout[11261]: Traceback (most recent call last):
Aug 15 18:41:07 debian11 airtime-playout[11261]:   File "/usr/bin/airtime-playout", line 4, in <module>
Aug 15 18:41:07 debian11 airtime-playout[11261]:     __import__('pkg_resources').run_script('airtime-playout==1.0', 'airtime-playout')
Aug 15 18:41:07 debian11 airtime-playout[11261]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 651, in run_script
Aug 15 18:41:07 debian11 airtime-playout[11261]:     self.require(requires)[0].run_script(script_name, ns)
Aug 15 18:41:07 debian11 airtime-playout[11261]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py" …
```

Rename isAlive method to is_alive

---

install
installer/vagrant/debian.sh

Apt should fail fast (and report) instead of
forcing a broken installation.
The version check is also not required anymore as
most distribution now provide an apt version > 1.1.

Remove install apt-get dangerous options

---

airtime_mvc/application/common/HTTPHelper.php
airtime_mvc/application/configs/conf.php
airtime_mvc/build/airtime.example.conf
airtime_mvc/tests/application/configs/ConfigTest.php

The PHP logic now matches the Python. Fixes: #1283
@Robbt would appreciate your review here, PHP is not a strong point for me
Restores #1284

correctly determine protocol from port and configuration in PHP

---

python_apps/api_clients/api_clients/version2.py

Scheduler should prepare 1 day ahead, not 1 hour.
The old API client v1 used to call the following action, and underlying schedule model:
https://github.com/LibreTime/libretime/blob/d6093f7356d262838e866deb80439dadf3220e78/airtime_mvc/application/controllers/ApiController.php#L720-L730
https://github.com/LibreTime/libretime/blob/d6093f7356d262838e866deb80439dadf3220e78/airtime_mvc/application/models/Schedule.php#L1118-L1140
The new API v2 prepared 1 hour of scheduled track instead
of 1 day in the old  API.
Fixes #1275

Fix api client v2 get schedule

---

install

On a new Ubuntu 18.04 installation, the script stops when trying to execute `build.sh`. Calling `bash` to launch the script fixes the issue.
I'm using my fix in order to install LibreTime on a new Ubuntu 18.04 installation.
Install LibreTime on a new Ubuntu 18.04 installation.
No links.

Fixing a permission bug in the install script.

---

python_apps/pypo/bin/airtime-liquidsoap
python_apps/pypo/bin/airtime-playout
python_apps/pypo/bin/pyponotify
utils/airtime-silan
utils/upgrade.py

Some systems only provide a versionned `python3` executable.

Fix python shebangs

---

python_apps/airtime_analyzer/requirements-dev.txt
python_apps/airtime_analyzer/tests/cuepoint_analyzer_test.py
python_apps/airtime_analyzer/tests/fixtures/__init__.py
python_apps/airtime_analyzer/tests/playability_analyzer_test.py

The CI pipeline discovered that we have some inconsistency across distribution with some tests.
For now, we could use some workaround until we properly fix the code.

Fix tests failing on buster

---

api/setup.py
python_apps/airtime-celery/setup.py
python_apps/airtime_analyzer/setup.py
python_apps/api_clients/setup.py
python_apps/pypo/setup.py

This requires #1318 because I am lazy resolving conflicts.
Updated all the setup.py files with recent project details.
Important change, I relicenced the airtime-celery service to AGPLv3, are we OK with that ? I don't know if this is legally ok ?

Update project details in setup tools.

---

python_apps/airtime_analyzer/requirements-dev.txt
python_apps/airtime_analyzer/tests/filemover_analyzer_test.py
python_apps/airtime_analyzer/tests/metadata_analyzer_test.py
python_apps/api_clients/requirements-dev.txt
python_apps/api_clients/tests/apirequest_test.py

mock was merged into stdlib, we should use the stdlib instead of the mock package.

Replace mock with stdlib unittest.mock

---

.github/annotations/pylint.json
.github/workflows/test.yml
.pre-commit-config.yaml
api/Makefile
api/setup.py
python_apps/airtime-celery/Makefile
python_apps/airtime-celery/setup.py
python_apps/airtime_analyzer/Makefile
python_apps/airtime_analyzer/requirements-dev.txt
python_apps/airtime_analyzer/setup.py
python_apps/api_clients/Makefile
python_apps/api_clients/requirements-dev.txt
python_apps/api_clients/setup.py
python_apps/pypo/Makefile
python_apps/pypo/setup.py
tools/Makefile
tools/python.mk
tools/requirements-dev.txt

- Enhance the way we manage development dependencies (slowly moving towards pyproject.toml file structure)
- Require python >=3.6
- Use a shared makefile for python apps
- Start linting every python app ! (With github annotations !)

Start linting :tada: !

---

python_apps/api_clients/api_clients/version1.py

Argument should be `_post_data` and we only allow kwargs in `ApiRequest.__call__`.

Fix bad argument name, use kwargs

---

airtime_mvc/application/controllers/ApiController.php

This allow calls to API v1 to authenticate using the Api-Key http header instead of query/path params.

Auth to API v1 using Authorization: Api-Key header

---

tools/python.mk

This allow to reinstall the packages without
rebuilding the venv in case of dependencies change.

Split venv setup and package install targets

---

api/setup.py
install

Also remove prod extra requires for api because ./setup.py install don't handle extra requires.
Closes #1350

Fix pip install failing with setuptools install-options (revert)

---

api/libretimeapi/models/schedule.py
api/libretimeapi/tests/models/test_schedule.py
api/libretimeapi/views.py
python_apps/api_clients/api_clients/version2.py

Should fix #1275
The logic is explained in the code comments. I hope that my assumptions are correct regarding the case where a scheduled item starts after the end of a show.

Fix cueout for schedule starts overlapping show ends  

---

python_apps/api_clients/api_clients/utils.py

Fix some name collisions...
```
2021-09-29 09:57:44,525 [version1] [ERROR]  type object 'datetime.time' has no attribute 'sleep'
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 147, in retry
return self.__req()
File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 139, in <lambda>
self.__req = lambda: self(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 122, in __call__
res.raise_for_status()
File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service …
```

Properly import sleep function

---

api/setup.py
install
python_apps/airtime_analyzer/install/systemd/libretime-analyzer.service
python_apps/pypo/install/systemd/libretime-liquidsoap.service
python_apps/pypo/install/systemd/libretime-playout.service

- Install the python apps with pip install instead of bare setuptools.
- Change script install prefix to default `/usr/local/bin`.
This will simplify the way we install/uninstall the python apps.
Closes #1343 
Related-To #1350
I tested this on Buster (vagrant) and didn't face any problems.
BREAKING: Previous entrypoints scripts should be removed from `/usr/bin`
```sh
sudo rm -f \
sqlformat \
django-admin \
django-admin.py \
markdown_py \
libretime-api \
mutagen-inspect \
mutagen-pony \
mid3cp \
mid3iconv \
mid3v2 \
moggsplit \
collectiongain \
replaygain \
libretime-analyzer \
airtime-playout \
pyponotify \
airtime-liquidsoap
```

Install python apps using pip

---

install

Fixes: #1434
Temporary revert until we can fix the quoting

fix: revert removal of eval for shell commands

---

.github/dependabot.yml

Not strictly necessary yet, but will make it fit in with #1180 when we get there

chore: add semantic-release prefix to dependabot commits

---

worker/setup.py

Hidden as they are included in airtime_analyzer, but also needed for celery.

fix: add missing dependencies to celery module

---

playout/setup.py

Until pip out-of-tree dependencies work with our setup and we can update to newer versions of our dependencies, assume api client is installed without explicitly adding it as a dependency. The install script installs api_client anyway
Fixes: #1435

fix: assume api client is installed

---

.github/dependabot.yml

Dependabot should catch up with our commit msg style, I propose we let it auto detect again.
Reverts: #1442

chore(ci): let dependapot catch up with commit syle

---

.github/workflows/closed-references.yml

This workflow will check for issue links in the code
that has been closed upstream and can be dealt with.

chore(ci): add closed references notificier workflow

---

.github/workflows/lint-pr.yml

This enforce semantic pull request messages before merging.
Do we want to require a scope or do we allow un-scoped prefixes ?
Did I miss a scope in the allowed scopes ?
The subjects should not start with a uppercase letter.

ci: add semantic pull request linting

---

.github/workflows/test.yml
shared/.pylintrc
shared/Makefile
shared/README.md
shared/libretime_shared/app.py
shared/libretime_shared/cli.py
shared/libretime_shared/config.py
shared/libretime_shared/logging.py
shared/libretime_shared/py.typed
shared/setup.py
shared/tests/config_test.py
shared/tests/logging_test.py

This adds a shared package usable by our python apps, to handle common tasks such as loading the logger, load a configuration file.
It the beginning of a series of PR that will start using this library in order to enhance the different apps.
This library assumes the following:
- We will use `Click` to create a proper CLI for each of our apps, allowing user and devs to tweak low level configurations and run advanced commands from the CLI.
- We will use `Loguru` instead of `logging`, for simplicity and loguru's power out of the box.
- We will wrap each of our log running functions (playout/liquidsoap/...) in a `App` class that will inherit from `libretime.shared.app.AbstractApp`. This Abstract app will setup common functionalities, and will have a consistent behavior across our tools.
- We …

feat: create libretime_shared package

---

shared/libretime_shared/config.py

- The path to the configuration file can be changed using env variables through the cli options. So maybe it isn't required to add this helper function.
- A default config filepath constant was created in order to prevent any possible duplication.

feat: enhance libretime shared

---

shared/libretime_shared/app.py
shared/libretime_shared/logging.py

Simplify the logger setup, as choice should be
left to the user to import or guess  the log level from verbosity.

feat(shared): let user provide the log level

---

Vagrantfile

This allows one to connect to 192.169.10.100 instead of localhost, and reduce port conflict with other services

chore: allow no port fowarding in vagrant

---

shared/libretime_shared/cli.py

Some few typing mismatch, the previously received type was actually a string.

fix(shared): change filepath options type to pathlib.Path

---

analyzer/packages.ini
api/packages.ini
playout/packages.ini

this will make the section more explicit,
in addition, this allow to exclude python deps
on docker images for example.

chore: rename common section to python

---

installer/vagrant/debian.sh

While this should be working out of the box, I had some issues when using `deb.debian.org`, and using the old mirrors urls fixed it. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986356
Fixes #1396

chore: add auto-apt-proxy to vagrant prepare

---

install
playout/.pylintrc
playout/Makefile
playout/install/logrotate/libretime-liquidsoap.conf
playout/install/systemd/libretime-liquidsoap.service
playout/install/systemd/libretime-playout.service
playout/libretime_liquidsoap/generate_liquidsoap_cfg.py
playout/libretime_liquidsoap/main.py
playout/libretime_playout/listenerstat.py
playout/libretime_playout/main.py
playout/libretime_playout/notify/main.py
playout/libretime_playout/pypofetch.py
playout/libretime_playout/pypofile.py
playout/libretime_playout/pypoliqqueue.py
playout/libretime_playout/pypoliquidsoap.py
playout/libretime_playout/pypomessagehandler.py
playout/libretime_playout/pypopush.py
playout/libretime_playout/recorder.py
playout/libretime_playout/telnetliquidsoap.py
playout/libretime_playout/testpypoliqqueue.py
playout/setup.py

feat(playout): enhance playout logging
Some initial work on modernizing the playout app. This replace any custom logger or
logging based logger with the logging tools from libretime_shared.logging and loguru.
Removed all the thread/function assigned logger (self.logger = ...), as this makes it
part of the logic (passing logger though function args) as it should not.
Of a dedicated logger is required for a specific task, it should use
the create_task_logger function.
- refactor: remove dead code
- refactor: remove py2 specific fix
- feat: remove unused test command
- feat: setup shared cli and logging tools
- feat: replace logging with loguru
- feat: setup shared cli and logging tools for notify
- fix: warn method deos not exist
- feat: make cli setup the entrypoint
- fix: install shared …

feat(playout): enhance playout logging

---

.github/RELEASE.md
.github/workflows/test.yml
.github/workflows/tools.yml
CONTRIBUTING.md
README.md
docs/_docs/contribute.md
docs/_docs/interface-localization.md
docs/_layouts/article.html
legacy/application/configs/constants.php

This rename all references to the `master` branch to `main`.
Once the default branch is renamed and this is merged, the following things are left to do:
- Update Weblate Pull/Push configuration
- Pin the #1277 issue to the issue tracker as notice for everyone.  
Fixes #1277

chore: rename master branch to main

---

.github/workflows/test.yml

This cancel previous test workflows. Based on https://stackoverflow.com/a/66336834

ci: cancel duplicate test workflow

---

installer/vagrant/debian.sh

First run works, but any extra run will break the source.list file.

fix: make vagrant source.list update idempotent

---

.github/workflows/test.yml
api/install/systemd/libretime-api.service
api/libretime_api/settings.py
api/libretime_api/utils.py

:warning: Do not squash
As side effect, this allow to run collect static without having a configuration file or log directory deployed. 
- feat(api): update env var settings loading
BREAKING CHANGE: environment variables names changed
"LIBRETIME_CONF_DIR" was removed
"LIBRETIME_CONF_FILE" was renamed to "LIBRETIME_CONFIG_FILEPATH"
- fix(api): duplicate exception raising and close file
- feat(api): allow to run without log file for dev
BREAKING CHANGE: moved production api log file
from '/var/log/airtime/api.log' to '/var/log/libretime/api.log'

feat(api): improve api settings

---

playout/libretime_liquidsoap/1.1/ls_lib.liq
playout/libretime_liquidsoap/1.1/ls_script.liq
playout/libretime_liquidsoap/1.3/ls_lib.liq
playout/libretime_liquidsoap/1.3/ls_script.liq
playout/libretime_liquidsoap/1.4/ls_lib.liq
playout/libretime_liquidsoap/1.4/ls_script.liq
playout/libretime_playout/notify/main.py
playout/setup.py

Fixes #1502
- replace notify option parser with click
- refactor call from liquidsoap to playout-notify
BREAKING CHANGE: the playout-notify log file in '/var/log/airtime/pypo-liquidsoap/notify.log' was removed and merged into the existing '/var/log/libretime/liquidsoap.log' log file.

feat(playout): migrate notify cli to click

---

analyzer/Makefile
analyzer/pyproject.toml
analyzer/setup.py
api/Makefile
api/pyproject.toml
api/setup.py
api_client/Makefile
api_client/pyproject.toml
api_client/setup.py
playout/.pylintrc
playout/Makefile
playout/pyproject.toml
playout/setup.py
shared/.pylintrc
shared/Makefile
shared/libretime_shared/config.py
shared/libretime_shared/logging.py
shared/pyproject.toml
shared/setup.py
shared/tests/config_test.py
tools/.pylintrc
tools/Makefile
tools/packages_test.py
tools/pyproject.toml
tools/python.mk
worker/Makefile
worker/pyproject.toml
worker/setup.py

Related to #1154 
This makes our different python package more consistent and use pep 517 with the pyproject.toml file for configuration.
This also starts making our linters fail in CI for some package: shared, tools
:warning: Please do not squash

chore: improve python packages configuration

---

legacy/composer.lock

In the propel fork I setup for libretime, I merged the changes from https://github.com/propelorm/Propel/pull/1086 as it brings a lot of fixes and it appears that his branch was working perfectly for over a year in one of the author's project. As I am not a propel / php expert I would rather rely on his code than mine. 
His branch passed the testsuite with php7.4, but I couldn't reproduce it, and didn't want to dig too much into it. If someone wants to make the testsuite pass, it would be great !
This PR will include these changes.
Maybe this can fix #1448, I haven't tested it yet, but that in my plans.

chore(legacy): upgrade propel1 dependency

---

legacy/application/controllers/ApiController.php
legacy/application/controllers/PlaylistController.php
legacy/application/models/Playlist.php

Should close #1448
More of those PR's might come in the future as we start using Libretime with php74. Hunting down every possible case would be a huge work, we should use and fix what is broken.

fix(legacy): make playlist model compatible with php74 null arrays

---

playout/install/systemd/libretime-liquidsoap.service
playout/libretime_liquidsoap/main.py

BREAKING CHANGE: When running liquidsoap as a systemd service, the working directory is now /var/lib/libretime/playout.

feat(playout): change liquidsoap working dir

---

legacy/application/Bootstrap.php
legacy/application/airtime-boot.php
legacy/application/configs/constants.php
legacy/build/airtime-php.logrotate
legacy/tests/application/bootstrap.php
legacy/tests/application/helpers/AirtimeInstall.php

BREAKING CHANGE: moved legacy log file from '/var/log/airtime/zendphp.log' to '/var/log/libretime/legacy.log'

feat(legacy): rename log filepath

---

legacy/application/configs/constants.php
legacy/build/airtime-setup/forms/media-settings.php

The installer hasn't been updated to create the default storage path.
Fixes #1562

fix(legacy): revert default storage path

---

.github/workflows/test.yml
api/libretime_api/settings.py
docs/_docs/host-configuration.md
docs/_docs/upgrading.md
legacy/application/configs/airtime-conf-production.php
legacy/application/configs/conf.php
legacy/application/models/Auth.php
legacy/application/upgrade/Upgrades.php
legacy/build/airtime.example.conf
legacy/tests/application/helpers/AirtimeInstall.php
legacy/tests/application/helpers/TestHelper.php
legacy/tests/config/airtime.conf

Add a port field (`database.port`) to the database config section.
BREAKING CHANGE: the database section in the config file has been updated:
- `database.dbname` was renamed to `database.name`
- `database.dbuser` was renamed to `database.user`
- `database.dbpass` was renamed to `database.password`

feat(legacy): add db config defaults and allow custom port

---

api/Makefile
api_client/Makefile
playout/Makefile
shared/Makefile
tools/python.mk
worker/Makefile

Please do not squash
Also set the default make target to install, so we don't automatically run lint, test, ... when running `make`

chore: setup bandit on python apps

---

analyzer/libretime_analyzer/pipeline/analyze_metadata.py
analyzer/setup.py
analyzer/tests/conftest.py
analyzer/tests/fixtures/__init__.py
analyzer/tests/fixtures/generate.sh
analyzer/tests/pipeline/analyze_metadata_test.py

- Upgrade mutagen to 1.45.1
- Remove custom wave data extraction
- Add .wav fixtures
- Move md5 sum in it's own function
- Cleanup comments
- Let analyze_cuepoints handle cuein and cueout metadata
Close #717

feat(analyzer): rework analyze_metadata step

---

analyzer/libretime_analyzer/pipeline/organise_file.py
analyzer/tests/conftest.py
analyzer/tests/pipeline/organise_file_test.py
analyzer/tests/pipeline/pipeline_test.py

The new behavior for duplicate file is now:
```
If you import multiple copies of the same file, the behavior is:
- The first filename is preserved.
- The next filenames receive the current date append to the name.
```
- use datetime instead of uuids
- massively using pathlib to manipulate paths
- append datetime is now in iso format
Related to #1592

feat(analyzer): rework organise_file using pathlib

---

shared/README.md
shared/tests/config_test.py

An extra test, as I wasn't sure of some behavior in the config models.

test(shared): config with required submodel

---

.github/workflows/housekeeping.yml

chore: ignore closed ref notifer on releases notes

---

install
worker/Makefile
worker/install/systemd/libretime-celery.service
worker/libretime_worker/__init__.py
worker/libretime_worker/config.py
worker/libretime_worker/tasks.py
worker/setup.py

BREAKING CHANGE: The worker `RMQ_CONFIG_FILE` environement variable has
been renamed to `LIBRETIME_CONFIG_FILEPATH`. In addition the systemd
working directory for the worker has changed from `/srv/airtime` to
`/var/lib/libretime/worker`.

feat(worker): load config using shared helpers

---

tools/extract-requirements.sh

Prevent a possible mismatch between new setup.py and old requires.txt in previous egg build.

chore: always build egg

---

.github/dependabot.yml

those packages need to be upgraded alongside with @docusaurus/core so we can ignore any individual version bump.

chore: ignore docusaurus extra packages upgrade

---

.github/workflows/tools.yml

This might fix a lot of false positive while downloading the
code to the testing folder.

ci: install git in libretime-dev testing image

---

install

This fixes the upgrade procedure for the python packages using the installer.
Whether this fixes the worker upgrade or not, we should upgrade the deps according to our requirements specs anyway.

fix: upgrade python packages during install

---

playout/libretime_liquidsoap/1.1/ls_lib.liq

Fix python36 encoding runtime error that was failing on bionic
Fixes #1606

fix(playout): add locales to libretime-playout-notify calls

---

.github/workflows/tools.yml

Related to 8c96c0a0949f2de637f9ca10e706162dcd96ef45

ci: add missing python3-venv package for testing

---

.github/workflows/api-schema.yml
api/Makefile
api/libretime_api/settings/testing.py

Allows automatic generation of api clients based on the Django schema. They still need testing, but the workflow is now up and running to generate them.

ci: generate schema and push to api-client repo

---

Makefile
tools/bump-python-version.sh
tools/version.sh

This will bump the version in the setup.py files before creating a tarball, I think we could do this during release and create a version bump commit.
Fixes #864

chore: add bump python version tool

---

docs/releases/unreleased.md
install
legacy/build/airtime-setup/load.php

BREAKING: The worker service no longer uses a dedicated `celery` user to run. The old `celery` user can be removed from the system.

feat(worker): don't run with a dedicated user

---

website/package.json
website/yarn.lock

The recent version bump #1859 for docusaurus only updated a single package, this upgrade all the docusaurus deps.

chore(deps): update dependency @docusaurus/* to v2.0.0-beta.21

---

shared/libretime_shared/config.py
shared/tests/config_test.py

This should make the `general.public_url` and `storage.path` consistent with regards to trailing slashes. Note that the PHP config does the opposite and always add a trailing slash.

feat(shared): add config trailing slash sanitizer

---

api/libretime_api/legacy/management/commands/set_icecast_passwords.py

Correctly implement the Preference.objects.update_or_create function.

fix(api): allow updating default_icecast_password

---

api/libretime_api/legacy/migrations/0032_3_0_0_alpha_13_6.py

This is supposed to work without it, but this is to be safe.

fix(api): cascade when dropping table

---

Vagrantfile
docs/admin-manual/setup/install.md
install

Services management should be handled by the admin. You can use the following command `systemctl restart  libretime.target` after the install/upgrade script.
Start/Stop/Restart of the services should be handled by the admin, we don't want to mess with missing migrations (This is a problem for legacy though, because the files are swapped and take effect immediately).

feat(installer): remove allow-restart flag

---

playout/libretime_playout/liquidsoap/entrypoint.py
playout/libretime_playout/liquidsoap/liquidsoap_auth.py
playout/libretime_playout/main.py
playout/libretime_playout/notify/main.py
playout/libretime_playout/player/fetch.py
playout/libretime_playout/player/file.py
playout/libretime_playout/player/push.py
playout/libretime_playout/recorder.py
playout/libretime_playout/stats.py

- Use legacy_client across playout code to make the difference between the old and new clients.
- Setup clients during initialization, and pass clients down to the different apps.

feat(playout): use single clients instance

---

.github/workflows/website-preview-command.yml

Should reduce the website-preview command verbosity by using a single comment to notify deployment status.

ci: website-preview use single comment

---

legacy/application/models/Preference.php

Load logo content from the local file instead of the public location.

fix(legacy): get local logo file

---

.github/workflows/_python.yml
.github/workflows/api.yml
.github/workflows/dev-tools.yml

Liquidsoap does not allow running as uid=0 or even gid=0 for some older versions. A setting to allow running as root has been added in 1.3.4, so bullseye is the only version supporting this setting.
This will allow running liquidsoap in CI for testing.
Related to #2051
The sudo package is always useful for debugging with tmate.

ci: add custom user for dev containers

---

installer/config.yml
legacy/application/models/StreamSetting.php

- Make it explicit that you should not reuse those fields, as they should always be specified.
- Add empty icecast output public_url field.
- Fix inconsistency between docs and outputs public_url code.

fix(installer): move non reusable fields from default output

---

install
shared/packages.ini

zoneinfo rely on the system tzdata package to work.

fix(shared): install tzdata distibutions package

---

install

Now that liquidsoap does not write any file in /etc/libretime, we can make it read only.

fix(installer): config dir should be read only

---

docker-compose.yml

Nginx is failing because of the missing php-fpm upstream server.
Do we prefer to have a 3rd layer of dependency (nginx > legacy > postgres and rabbitmq) or should we configure nginx to retry multiple times before failing ?

fix: nginx depends on legacy in docker-compose

---

Vagrantfile

- We restart services such as postgresql and it generates confusing logs.

chore: run vagrant post-install before libretime start

---

.chglog/CHANGELOG.md.tpl
.chglog/config.yml
CHANGELOG.md
Makefile
docs/developer-manual/development/releases.md
tools/changelog.sh

I am not totally happy with the workflow, we will have to fine tune this along the way.
This only generate a specific tag changelog and prepend it to the existing changelog. This allow us to fix spelling errors and keep the fixes by not regenerating the entire changelog. 
The tag will always be the latest tag in the current branch, unless passed as env var `tag=3.0.0-alpha.12 make changelog`.
The changelog does not contain breaking changes as they are in the upgrade procedure. The BREAKING CHANGE commit messages foot notes doesn't allow later editing, so we should keep using them but we should document upgrade procedure in the release notes.
~~This puts a hard dependency on git-chlog, don't know if we have some better alternatives. Maybe we want to embrace a fully featured tool such as …

chore: add changelog generator

---

playout/install/systemd/libretime-playout.service

Do not set a hard requirement on the service, only define the startup order.

fix: start playout service after liquidsoap

---

.github/workflows/project.yml
.pre-commit-config.yaml
Makefile

Puts a hard dependency on docker if we want to run pre-commit, but this is easier than having to install the many shfmt/shellcheck/... tools on the system.

chore: move shell tools to pre-commit (via docker)

---

docs/developer-manual/development/environment.md

This is required for the --mount cache used to cache pip packages - https://docs.docker.com/build/buildkit/#getting-started

docs: add DOCKER_BUILDKIT environment variable

---

.github/renovate.json

Actually enable renovate for 3.0.x, the change must be done on the default branch, not on the target branch as I did here: 3694b316105a88c73b630a43304e55bc3c92f1a1

ci: enable renovate for 3.0.x

---

legacy/application/common/TaskManager.php

This should give us more insight on whether tasks are run or not. Maybe it is a bit verbose, but that's what logs are for ?!

fix(legacy): add log entry on task run

---

.gitignore
Makefile

This will clone the website repo, install the website dependencies and override the docs path to the current main repository docs path.

chore: add docs dev setup with the website

---

legacy/application/models/Datatables.php
legacy/application/models/StoredFile.php

Advanced where clause didn't support matching integers (primary keys).
Fix #2344

fix(legacy): advanced search by track type id

---

docs/admin-manual/troubleshooting.md
legacy/application/common/CORSHelper.php
legacy/application/configs/constants.php
legacy/application/views/scripts/error/error-500.phtml
tools/packages.py

Add a link to the troubleshooting docs on the error page.
I hope this will guide the users to the troubleshooting guide first before the discourse forum.
The cors log message is now a bit more explicit and might help users to understand why they cannot login.

fix(legacy): improve error messages and troubleshooting

---

install

The error was previously not printed.
supported distribution

fix(installer): print unsupported distribution error

---

legacy/application/common/FileDataHelper.php

While removing a custom artwork the audio file is also deleted.
No
No
This bug does only appear with custom cover images.
The default ones are not affected because they are in a different folder than the custom ones
1. Edit track
2. Add custom cover image and save
3. remove cover image => audio_file deleted
1. Edit track
2. Add custom cover image and save
3. remove cover image => audio_file is not deleted

fix(legacy): do not delete audio file when removing artwork

---

legacy/application/controllers/ApiController.php

Fixes https://discourse.libretime.org/t/onairlightaction-errors-out-but-light-is-on-in-the-ui/1421

fix(legacy): on air light fails when no shows are scheduled

---

.github/workflows/analyzer.yml
.github/workflows/api-client.yml
.github/workflows/api-schema.yml
.github/workflows/api.yml
.github/workflows/legacy.yml
.github/workflows/playout.yml
.github/workflows/project.yml
.github/workflows/shared.yml
.github/workflows/worker.yml

Since we have a protection on the main branch the locales update could not push the changes to the main branch this night.
https://github.com/libretime/libretime/actions/runs/4278223004/jobs/7455414545
We should probably use the libretime-bot token to clone and push the changes.
The job succeeded on my fork, but I think this was not my intention haha. I limited the job to only run on the repo.

ci: pull code before updating locales

---

README.md

Fallback to the alternative if the image cannot be loaded (e.g. dockerhub + CORS)
Or for example on Github (this should not happen since we can load the image on Github):

chore: use title for image alternative

---

playout/libretime_playout/liquidsoap/1.4/ls_script.liq

Liquidsoap did a harsh cut at the end of every show.
This MR fixes this an (re)enables settings for the crossfading by
- adding the values "default_crossfade_duration", "default_fade_in" and "default_fade_out" from the "preference" page to the StreamPreferences api.
- The new values are then used while generating the liquidsoap entrypoint, and can also be changed  via telnet.
Created a VM, installed my Libretime branch, scheduled some shows to hear the fade at the end of the show. 
I also run "make test" in the "playout" folder.
Closes: #2070 
https://discourse.libretime.org/t/how-to-fade-out-shows/700
https://discourse.libretime.org/t/no-fadestop-at-the-show-end/1412

fix(playout):  when shows ends, next shows starts without fade-in/fade-out 

---

docs/admin-manual/monitoring.md

We are lacking an easy way to install the sentry extra using the installer, but since this is for power users I assume they know how to handle this.
I'll include an option to install the sentry extra in the ansible role.

docs: add instructions for the sentry setup

---

api/libretime_api/settings/prod.py
api/libretime_api/settings/testing.py
docker/config.dev.yml
docker/config.yml
docker/example/config.yml
docs/admin-manual/setup/configuration.md
install
installer/config.yml
legacy/application/configs/conf.php
shared/libretime_shared/config/_models.py

Related to #2426
This adds a warning about a future required configuration field, that will fallback to the previous behavior (use the `general.api_key` as secret_key) in case of a missing value. We must make the field required on the next major version bump, we will keep track of this in #2426.
New LibreTime setup will have the secret_key field filled during the install process.

feat: use secret_key config field instead of api_key

---

api/libretime_api/core/models/preference.py

fix(api): cast string value to int enum (#2461)
c7381a4f809114708838f86aead0d9c769bc3b79

chore: backport #2461

---

legacy/application/assets.json
legacy/public/js/airtime/library/library.js

The show builder was printing the track type ID instead of printing the expected track type code.

fix(legacy): don't print track_type id in show builder table

---

legacy/Makefile

- Disable plugins or script when running composer
- Export COMPOSER_ALLOW_SUPERUSER=true to suppress the warning
- Simplify makefile to build legacy files

fix(legacy): remove composer superuser warning

---

legacy/application/assets.json
legacy/public/js/airtime/library/library.js

Use a different storage key for datatable settings for the dashboard and builder views. The settings were overwritten when the other view was loaded.

fix(legacy): keep datatable settings between views

---

analyzer/setup.py
api-client/setup.py
api/setup.py
docs/releases/3.1.0.md
docs/releases/README.md
docs/releases/unreleased.md
playout/setup.py
shared/setup.py
worker/setup.py

I'd like to start thinking about releasing 3.1.0.
There are some issues still open on the 3.1.0 milestone, I've moved some of them to the 3.2.0 milestone. Is there anythingelse that must go into 3.1.0 ?

chore: release 3.1.0

---

playout/libretime_playout/liquidsoap/templates/outputs.liq.j2
playout/tests/liquidsoap/entrypoint_test.py

The aac output template was broken, only found out while going over #2569 again.

fix(playout): liquidsoap aac output syntax errors

---

docker-compose.yml

The default docker composition had several problems like leaking processes and high lsof cpu usage. The processes were leaking because of [this call](https://github.com/libretime/libretime/blob/3.1.0/playout/libretime_playout/liquidsoap/1.4/ls_lib.liq#L2) and no init process to reap the processes once they finished. The [lsof](https://github.com/libretime/libretime/blob/3.1.0/playout/libretime_playout/player/fetch.py#L224) thing [is a know issue with docker](https://bugzilla.redhat.com/show_bug.cgi?id=1715254).
_Ran libretime with these changes and everything worked as expected_
_Run the docker composition and observe process leak and high cpu usage:_
```
root     3192950  0.0  0.0 720496  9588 ?        Sl   04:03   0:00 …
```

fix: libretime process leaks and lsof high cpu usage

---

docker/config.template.yml
docker/config.yml
docker/example/config.yml
docs/admin-manual/configuration.md
installer/config.yml
legacy/application/configs/conf.php
legacy/application/models/StreamSetting.php
shared/libretime_shared/config/_models.py

Allow to configure streams to be used for mobile devices. The field was removed while moving to the new config file, the feature should be working :tm: .

feat: add mobile devices stream config field

---

legacy/application/models/Preference.php

This allows to debug when the exception is raised. I've been facing this for a few weeks now, only noticed it now.

fix: add parent function name in setValue exception

---

api/libretime_api/permission_constants.py
api/libretime_api/schedule/models/show.py
api/pyproject.toml

Django models will generate too much false positives.

chore(api): disable duplicate-code check

---

api/schema.yml

drf-spectular now properly split the different kind of enums.

fix(api): enum schema description

---

.github/workflows/release-please.yml

By default, Release Please uses the built-in GITHUB_TOKEN secret. However, all resources created by release-please (release tag or release pull request) will not trigger future GitHub actions workflows, and workflows normally triggered by release.created events will also not run.

ci: ensure release pipeline run after tag

---

legacy/application/models/Block.php

Closes #2798
COALESCE last played null values with date -infinity, to ensure newly added files are found by the last played smart block criteria.

fix(legacy): ensure last played criteria works with never played files

---

docker/config.template.yml
docker/config.yml
docker/example/config.yml
docs/admin-manual/configuration.md
docs/releases/unreleased.md
installer/config.yml
legacy/application/configs/conf.php
shared/libretime_shared/config/_models.py

BREAKING CHANGE: The default system output (`stream.outputs.system[].kind`) changed from `alsa` to `pulseaudio`. Make sure to update your configuration file if you rely on the default system output.
Closes #2542

feat!: default system output is now `pulseaudio`

---

Dockerfile
api/install/systemd/libretime-api.service

Fix this Django exception: Django can only handle ASGI/HTTP connections, not lifespan.

feat: disable uvicorn worker lifespan

---

worker/libretime_worker/tasks.py

When the episode URL return a 404, the tmp_file is never set, and we have an unbound variable exception.

fix(worker): unbound variable when episode url returns HTTP 404

---

docker/config.template.yml
docker/config.yml
docker/example/config.yml
docs/admin-manual/configuration.md
installer/config.yml
legacy/application/configs/conf.php
playout/libretime_playout/liquidsoap/templates/outputs.liq.j2
playout/tests/liquidsoap/__snapshots__/entrypoint_test.ambr
playout/tests/liquidsoap/fixtures/__init__.py
shared/libretime_shared/config/_models.py

Attempting to add hardware configuration to liquidsoap so that users may set hardware output in config.yml. I'm focusing my efforts on ALSA for now, but PulseAudio should be easy enough to implement after ALSA is successful.
Add hardware configuration
I'm using docker-compose on Ubuntu 20.04.
```
docker --version
Docker version 20.10.25, build 20.10.25-0ubuntu1~20.04.1
```
```
docker-compose --version
Docker Compose version v2.20.2
```
see my forum post for full notes:
https://discourse.libretime.org/t/hardware-configuration/1229/12

feat(playout): configure device for alsa and pulseaudio system outputs

---

docs/admin-manual/install/install-using-the-installer.md
install

Related to #2543
BREAKING CHANGE: The `--update-nginx` flag was removed from the installer. The nginx configuration deployed by the installer will now always be overwritten. Make sure to move your customizations to a reverse proxy configuration.

feat(installer)!: remove the `--update-nginx` flag

---

Dockerfile
api/install/systemd/libretime-api.service
api/libretime_api/gunicorn.py

Passing the --lifespan flag to gunicorn does not forward the option to uvicorn.

fix(api): move gunicorn worker config to python file

---

Vagrantfile
docker-compose.yml
docker/nginx.conf
docs/admin-manual/install/install-using-the-installer.md
docs/admin-manual/install/reverse-proxy.md
install

Closes #2575
Closes #2543
BREAKING CHANGE: The default listen port for the installer is now `8080`. We recommend that you put a reverse proxy in front of LibreTime.

feat(installer)!: change default listen port to 8080

---

api/libretime_api/storage/views/file.py
docker-compose.yml
docker/config.template.yml
docker/config.yml
docker/example/config.yml
docker/nginx.conf
docs/admin-manual/configuration.md
install
installer/config.yml
installer/nginx/libretime.conf

Closes #2522
To reduce the strain on the API service, we moved the media file serving to the Nginx web server. The API is still handling the authentication, but delegates the serving using the `X-Accel-Redirect` header.
BREAKING CHANGE: The media file serving is now handled by Nginx instead of the API service. The `storage.path` field is now used in the Nginx configuration, so make sure to update the Nginx configuration file if you change it.

feat!: use nginx to serve media files

---

install
installer/nginx/libretime.conf

Add the `--storage-path` flag to the installer to configure a custom storage path out of the box.
On existing installation, we check that the 'storage.path' in the configuration file is the same as the one provided by the installer. This ensures that we don't update the nginx configuration file with an invalid storage path.

feat(installer): add the `--storage-path` flag

---

api/libretime_api/storage/views/file.py

Use the filepath_to_uri function instead.

fix(api): paths with question marks chars are handled by X-Accel-Redirect

---

legacy/application/views/scripts/dashboard/stream-player.phtml

The Player on the dashbaord does not correctly play an AAC stream. The rewritng logic only takes into account the ogg format. Add rewriting from aac to m4a in the javascript calls so the player works.
AAC output currently only works with replacing liquidsoap, so technically this is a new feature.
The dashboard player is not documented. The player widget works with AAC streams already.
Swapped liquidsoap and reconfigured the default mp3 stream as AAC
on ubuntu focal, drop in the upstream liquidsoap deb to enable aac, then configure the secondary output to use 128kbit aac instead of mp3. Restart the target, login to the dashboard and open the …

feat(legacy): add aac/opus support to dashboard player

---

.github/workflows/container.yml

Pin docker/metadata-action to 5.4 until https://github.com/docker/metadata-action/issues/381 is fixed

ci: pin docker/metadata-action to working version

---

legacy/application/controllers/PreferenceController.php

lot of streams forbid http://libretime.example.org/preference/stream-setting to open (max=4)
this patch prevent the crash by displaying an error message and truncate streamcount to 4.

fix(legacy): avoid crash when lot of streams in configuration

---

analyzer/libretime_analyzer/pipeline/_ffmpeg.py

fix(analyzer): backslash non utf-8 data when probing replaygain

---

legacy/application/forms/EditAudioMD.php

this removes a visual gap between artwork and editor fields. I stumbled across this while updating the form to include replay gain.

fix(legacy): fix hidden fields in edit file form

---

api/libretime_api/core/models/preference.py
api/libretime_api/core/serializers/stream.py
api/libretime_api/core/tests/models/test_preference.py
api/libretime_api/core/tests/views/test_stream.py
api/libretime_api/core/views/stream.py
api/schema.yml
playout/libretime_playout/liquidsoap/models.py
playout/libretime_playout/player/schedule.py
playout/tests/conftest.py
playout/tests/liquidsoap/entrypoint_test.py
playout/tests/player/schedule_test.py

The replay gain preferences are applied in the legacy code, but the playout code was missing this feature. The replay gain was not applied when playout fetched the schedules.
https://github.com/libretime/libretime/blob/37d1a7685e37e45734553a0eb4a4da793ca858cb/legacy/application/models/Schedule.php#L881-L886

fix: apply replay gain preferences on scheduled files

---

legacy/application/assets.json
legacy/public/js/airtime/tracktype/tracktype.js

This is a minor nag i had. Since moving to an indexed track_type model for 3.0 the constraint of the shortlabel being immutable is no longer valid, since it's not used as index any more. This commit removes the readonly flag from that form field.

fix(legacy): allow updating track types code

---

docs/admin-manual/tutorials/setup-liquidsoap-aac-streaming.md

This adds reference to a second file needed for debian 11.

docs: get libfdk-aac from non-free source for debian 11

---

docker-compose.override.yml
docker-compose.yml

There is no docker compose file version 3.9, see https://docs.docker.com/compose/compose-file/compose-versioning/. The `init` command is used in the compose file and I wonder if we can set this to 3.7. When I followed the docs here https://libretime.org/docs/admin-manual/install/install-using-docker/, I was unable to get the docker compose to work because of a version issue. So I upgraded docker (on Ubuntu focal) but realised that 3.9 isn't even mentioned on the Docker website. 3.8 is, which I tried to use but it failed. 3.7 worked for me.
Docs are not affected.
I was following the [docs](https://libretime.org/docs/admin-manual/install/install-using-docker/) but then rand into a docker compose file version …

fix: incorrect docker compose version

---

docs/admin-manual/install/install-using-the-installer.md
docs/admin-manual/install/reverse-proxy.md

The upload limits settings are configured in the libretime nginx config, but must also be part of the reverse proxy.

docs: prevent reverse proxy from constraining the upload limits

---

legacy/application/controllers/TracktypeController.php
legacy/application/forms/AddTracktype.php

Fixes #2939
The zend form validation was not performed, only a custom method to validate the code was used. This merge both validation, and leverage the Zend form validation framework.
Also allow updating the track type code from the track type form. Related to #2955

fix(legacy): ensure validation is performed on the track type form

---

legacy/tools/composer.json

This should remove the update entries from the release-please changelog, as renovate will now consider updates for this dep as `chore` and not `fix`.

chore: mark php-cs-fixer as dev dependency

---

Dockerfile
api-client/libretime_api_client/v1.py
worker/Makefile
worker/install/systemd/libretime-worker.service
worker/libretime_worker/config.py
worker/libretime_worker/tasks.py

This ensures that when the LibreTime interface is not used for a long
time, we still have the task manager run essential tasks for the schedule.
Related to #2670

fix: trigger legacy tasks manager every 5m

---

Dockerfile
worker/install/systemd/libretime-worker.service
worker/libretime_worker/main.py
worker/setup.py

Allow us to be more flexible with the option passed the celery worker, for example, to change the logging level.

feat: start celery worker programmatically

---

install

Worker service fails after upgrade.
Related to #2988

fix(installer): setup the worker entrypoint

---

legacy/application/controllers/PreferenceController.php
legacy/application/controllers/plugins/RabbitMqPlugin.php
legacy/application/models/tests/populator.php
playout/libretime_playout/player/fetch.py
playout/libretime_playout/player/schedule.py

Build and use the schedule events only in playout, the events generated by legacy are not used anymore.
This ensure that we don't have to maintain 2 different implementation in 2 different languages. We still need the php function to run to make sure the side effects of this function are executed (filling the schedule in the DB).

feat: build schedule events exclusively in playout

---

legacy/application/models/StoredFile.php

when calling DELETE /rest/media/<id> the call fails with 'unknown error' if it's not within a GUI session. The StoredFile delete method checks for user permissions regardless of if a user is even known.

fix(legacy): allow deleting file with api token

---

api/libretime_api/schedule/models/schedule.py
api/libretime_api/storage/tests/views/test_file.py
api/libretime_api/storage/views/file.py

Description
This adds a implementation of file delete to the Django API. Right now the code will only manipulate the database but leave the file in place.
No documentation change is needed as the API Documentation is auto-generated from the code.
Testing Notes
Playground server with new code successfully executed DELETE api call.

feat(api): implement file deletion

---

worker/libretime_worker/main.py

The celery seem to ignore the first flag when `worker` is not part of the `argv`.

fix(worker): ensure celery beat is started

---

playout/tests/liquidsoap/client/conftest.py

See https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/contextmanager-generator-missing-cleanup.html

test: ensure the context cleanup is executed

---

install

Related to https://github.com/libretime/libretime/issues/2983

fix: pin pip version to <21.4 to allow installing pytz (celery)

---

install
tools/python.mk

Related to https://github.com/libretime/libretime/issues/2983

fix: pin pip version to <24.1 to allow installing pytz (celery)

---

docs/releases/4.2.0.md

Forgot to prepare the release note for v4.2.0.

docs: add missing v4.2.0 release note

---

Dockerfile

docker wants the 'AS' in uppercase if the 'FROM' is also in uppercase
These warnings are eliminated with this patch
``` => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)                                                                                                                                    0.1s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 21)                                                                                                                                   0.1s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 51)                                                                                                                                   0.1s
=> WARN: FromAsCasing: 'as' and …
```

fix: docker warnings "keywords casing do not match"

---

.github/workflows/housekeeping.yml

Ubuntu no longer maintains the package list for bionic. Linked to from old release notes

ci: fix broken link check

---

api/setup.py

This is until upstream fixes https://github.com/typeddjango/django-stubs/issues/2304

ci: downgrade django-stubs to not install v5.x

---

legacy/application/models/Block.php

It is good to have a deterministic order when doing explicit file sorting. This sorts by filename when last played time is null. I would expect filename to be the next sort after last played time in case of a tie, and was surprised to find it was not explicit. It should not break any existing use cases.
Kind of?
I did not update any documentation as this way seems like the logical expected way to do the sort.
I loaded up some tracks into a local libretime instance, let some of them play, and tested that all the old sorts worked as before as well as tracks getting sorted by filepath in case of a last played time

feat(legacy): order by filename when lptime is null

---

legacy/application/assets.json
legacy/application/controllers/LibraryController.php
legacy/application/models/StoredFile.php
legacy/application/views/scripts/library/edit-file-md.phtml
legacy/public/js/airtime/library/library.js

Add File Name and Size to the metadata editor screen, and added a File Name column to the tracks data table.
Yes
No, just some simple UI additions so no documentation needed.
I uploaded some tracks, clicked on edit, and saw that the filename and size showed up at the top. I also went out to the tracks view and added the File Name column and saw that the filename displayed properly.
Do what I did
Fixes #3053

feat(legacy): show filename and size on edit page and add filename datatable column

---

api/libretime_api/legacy/migrations/0006_2_5_5.py
api/libretime_api/legacy/migrations/0015_2_5_17.py
api/libretime_api/legacy/migrations/0023_3_0_0_alpha_9_1.py
api/libretime_api/legacy/migrations/_migrations.py

This fixes various problems in legacy migrations that were preventing a successful database migration from Airtime 2.5.1.  Previously, following [the procedure](https://libretime.org/docs/admin-manual/install/migrate-from-airtime/) using the migrations provided in the Libretime 4.2.0 installer, without the fixes in this PR, would either fail completely, or cause all of the imported data to be completely deleted. 
_migrations.py
If schema_version is not found in the table cc_prefs, it then checks for system_version to have a value of '2.5.1' (in case this is an airtime 2.5.1 migration which will not have any schema_version in cc_pref).  If found, it prevents loading of the schema file, which is critical to preserving the imported Airtime data.
0006_2_5_5
Removed a redundant addition of the …

fix(legacy): migrations from airtime 2.5.1

---

api/libretime_api/storage/tests/views/test_file.py
api/libretime_api/storage/views/file.py
api/schema.yml

Added filters for genre and md5 to the files API, e.g. `/api/v2/files?genre=soul`
**This is a new feature**: Yes
**I have updated the documentation to reflect these changes**: No
There should be a schema and docs that are generated automatically. I don't know where that is.
- Used docker to deploy locally
- Confirmed filters work at http://localhost:8080/api/v2/files?genre=Soul
- `make clean dev`
- Upload some files!
- Visit http://localhost:8080/api/v2/files
- You can use the filters
_How can the reviewer validate this PR?_
- See above
- wrote tests to confirm filters work

feat(api): added filters on genre & md5 for files api

---

.pre-commit-config.yaml

This is a way of ensuring the schema is up to date with every change. This should be extended by fixing the PR api schema pipeline to squash down all PR commits into a single change and checking the API schema for that. Otherwise people will fix the schema after a failed pipeline and the pipeline will continue to fail

chore: add pre-commit API check

---

legacy/application/assets.json
legacy/public/js/libs/CSVexport.js

…ance.
The existing implementation for exporting playout logs to a CSV file incorporates a very simplified CSV format. Some aspects of the complete [RFC](https://www.rfc-editor.org/rfc/rfc4180) are missing, such as escaping of quotes, and quoting of fields that contain certain characters.  This is problematic for common office spreadsheet tools, and practically, anything else.  Many radio stations rely on this functionality  to work well for exporting playout data, for example, in order to compile data for reporting requirements.
The changes in this PR add quoting of fields containing a comma, as well as those containing a CR/LF. It also escapes quotes by doubling them.  I'm not sure it makes CSVexport.js completely RFC 4180 compliant, but it is much closer than …

fix(legacy): additional specifics added to CSVexport.js for RFC 4180

---

legacy/application/assets.json
legacy/public/js/airtime/audiopreview/preview_jplayer.js

Added support for previewing FLAC files in the web interface, provided in #509 by marmotte32 on Github in the comments for this issue.
I have tested this against a script-installed copy of 4.2.0, and FLAC preview is working, although auto-play isn't.  I haven't tested to confirm if this behavior matches MP3 and OGG uploads.
_Do the changes in this PR implement a new feature?_
No changes needed; this bug is a missing file format in preview, and it requires no updates to the documentation.
I installed a LibreTime 4.2.0 system using the default installation script against a fully-updated, brand new Debian 11 system.  I logged into the web interface, uploaded some FLAC files, and …

feat: add flac support to Web player

---

.github/workflows/api-schema.yml

PRs are intended to be squashed to a single commit. Only checking the last commit gives us the intended state of the repo and ensures that if the author commits the schema fixes later, the CI passes as expected. Currently, the CI will fail because the earlier commits still have an out of date schema.

ci: only check last commit for API schema in PRs

---

playout/libretime_playout/player/file.py

Improves the way hashlib is called in libretime_playout/player so that  is isn't broken on systems with python < 3.9 
The way it is currently called in site-packages/libretime_playout/player/file.py, in the section where scheduled files are copied to the cache dir for playout, specifies the usedforsecurity=False flag as follows:
`hasher = hashlib.md5(usedforsecurity=False)`
hashlib.md5 did not support this flag until Python 3.9.  Attempting to specify the flag directly as an argument to hashlib.md5(), in an older python environment (such as that in Ubuntu Focal 20.04), is unsafe, and can cause hashlib.md5() to balk/throw an exception, which results in file copy operations failing.  This then precipitates into playout problems, as scheduled media is missing from the cache folder.
This PR …

fix(playout): improve the way hashlib is called in libretime_playout/player

---

playout/libretime_playout/liquidsoap/2.0/ls_lib.liq
playout/libretime_playout/liquidsoap/2.0/ls_script.liq

add Liquidsoap2.0 files
(port syntax 1.4 to 2.0)
I ran libretime on ubuntu 22.04 and liquidsoap2.0
this pr is just the beginning, just 2 files added it's a clean one...
in order to work under 22.04,it requires changes in
1.  this pr
1. (https://github.com/libretime/libretime/pull/2789)
1.  libretime/propel (https://github.com/libretime/propel1/pull/1)  or change legacy /composer.json
```    "type": "vcs",
-       "url": "https://github.com/libretime/propel1"
+       "url": "https://github.com/mp3butcher/propel1"
},
{
"type": "vcs",
@@ -30,7 +30,7 @@
"james-heinrich/getid3": "^1.9",
"league/uri": "^6.7",
"libretime/celery-php": "dev-main",
-     "libretime/propel1": "dev-main",
+    "mp3butcher/propel1": "main",
"php-amqplib/php-amqplib": "^3.0",
```
4.  and few mods in install
```  case …
```

feat(playout): add Liquidsoap 2.0 support

---

.github/workflows/docs.yml

Vale CI is broken until https://github.com/errata-ai/vale/issues/995 is addressed

chore(deps): update vale to v3.11.2

---

legacy/application/models/RabbitMq.php
playout/libretime_playout/message_handler.py

Currently, only one service can listen to libretime schedule change events. This change allows for as many services as desired to listen for schedule change events.
Yes
No, as this seems like the obvious default
I created 2 playout blocks, connected them both to the fanout queue and saw that they could all connect and receive schedule change events at the same time.
See testing notes

feat: use fanout queue type for playout queue

---

api/libretime_api/storage/management/commands/bulk_import.py
api/libretime_api/storage/models/library.py
api/libretime_api/storage/tests/management/commands/test_bulk_import.py

Uploads with bulk_import defining --library fail with error 400 in the REST API
The primary key of the track_type was changed from chars to a numerical ID, and the data model expects this now in the REST endpoint. However the bulk import still populates this field with the Char Tag.
`libretime-api bulk_import --path /home/libretime/upload/ --library POD --allowed-extensions mp3`
see above

fix(api): file upload with library
